# ============================================================
# GENERATED BY: CALM Forge v0.2  [BETA: Terraform Policy tests]
# One test per emitted policy. Run with: tfpolicy test
# DO NOT EDIT — regenerate from CALM source
# ============================================================

test "enforce_encryption_at_rest_passes" {
  mock "azurerm_storage_account" {
    # compliant fixture — the policy must PASS against this
  }
  expect_pass = policy.enforce_encryption_at_rest
}

test "deny_public_endpoints_passes" {
  mock "kubernetes_ingress_v1" {
    # compliant fixture — the policy must PASS against this
  }
  expect_pass = policy.deny_public_endpoints
}

test "cost_advisory_passes" {
  mock "plan.cost_estimate" {
    # compliant fixture — the policy must PASS against this
  }
  expect_pass = policy.cost_advisory
}

test "require_data_classification_tag_passes" {
  mock "azurerm_storage_account" {
    # compliant fixture — the policy must PASS against this
  }
  expect_pass = policy.require_data_classification_tag
}
