# ============================================================
# GENERATED BY: CALM Forge v0.2  [BETA: Terraform Policy]
# Compliance scope: pci-dss | Data classification: confidential
# tfpolicy is beta upstream (HashiCorp). Syntax may change until GA.
# DO NOT EDIT — regenerate from CALM source
# ============================================================


# Encryption at rest — PCI-DSS 3.4
policy "enforce_encryption_at_rest" {
  enforcement_level = "mandatory"

  resource_policy "azurerm_storage_account" {
    enforce {
      condition = attrs.enable_https_traffic_only == true
    }
  }

  resource_policy "azurerm_managed_disk" {
    enforce {
      condition = attrs.encryption_settings != null && attrs.encryption_settings.enabled == true
    }
  }

}

# No public endpoints — PCI-DSS 1.3
policy "deny_public_endpoints" {
  enforcement_level = "mandatory"

  resource_policy "kubernetes_ingress_v1" {
    enforce {
      condition = attrs.metadata.annotations["kubernetes.io/ingress.class"] != "public"
    }
  }

  resource_policy "kubernetes_service_v1" {
    enforce {
      condition = attrs.spec.type != "LoadBalancer" || attrs.metadata.annotations["service.beta.kubernetes.io/azure-load-balancer-internal"] == "true"
    }
  }

}

# Cost governance (advisory) — payments-portal
policy "cost_advisory" {
  enforcement_level = "advisory"

  cost {
    condition = plan.cost_estimate.delta_monthly_cost < 500
  }

}

# Cost governance (soft limit)
policy "cost_soft_limit" {
  enforcement_level = "soft-mandatory"

  cost {
    condition = plan.cost_estimate.delta_monthly_cost < 5000
  }

}

# Cost governance (hard limit)
policy "cost_hard_limit" {
  enforcement_level = "mandatory"

  cost {
    condition = plan.cost_estimate.delta_monthly_cost < 25000
  }

}

# Tagging requirements — confidential data classification
policy "require_data_classification_tag" {
  enforcement_level = "mandatory"

  resource_policy "*" {
    enforce {
      condition = attrs.tags != null && contains(keys(attrs.tags), "data-classification")
    }
  }

}
