# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault PKI and database engine configuration for fraud-detection-pipeline

# --- PKI: decision-to-gateway (decision-emitter → payment-gateway) ---

resource "vault_mount" "pki_fraud_detection_pipeline" {
  path                      = "pki/fraud-detection-pipeline"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_fraud_detection_pipeline_intermediate" {
  backend     = vault_mount.pki_fraud_detection_pipeline.path
  type        = "internal"
  common_name = "fraud-detection-pipeline Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "decision_emitter" {
  backend          = vault_mount.pki_fraud_detection_pipeline.path
  name             = "decision-emitter"
  allowed_domains  = ["decision-emitter.fraud-detection.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "payment_gateway" {
  backend          = vault_mount.pki_fraud_detection_pipeline.path
  name             = "payment-gateway"
  allowed_domains  = ["payment-gateway.fraud-detection.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}
