# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault policies for fraud-detection-pipeline components
# Compliance scope: pci-dss

# --- Policy: transaction-ingest ---
path "kv/data/fraud-detection-pipeline/transaction-ingest/*" {
  capabilities = ["read", "list"]
}

path "transit/encrypt/fraud-detection-pipeline" {
  capabilities = ["update"]
}
path "transit/decrypt/fraud-detection-pipeline" {
  capabilities = ["update"]
}

# --- Policy: ml-scoring ---
path "kv/data/fraud-detection-pipeline/ml-scoring/*" {
  capabilities = ["read", "list"]
}

path "transit/encrypt/fraud-detection-pipeline" {
  capabilities = ["update"]
}
path "transit/decrypt/fraud-detection-pipeline" {
  capabilities = ["update"]
}

# --- Policy: external-state ---
path "kv/data/fraud-detection-pipeline/external-state/*" {
  capabilities = ["read", "list"]
}

path "transit/encrypt/fraud-detection-pipeline" {
  capabilities = ["update"]
}
path "transit/decrypt/fraud-detection-pipeline" {
  capabilities = ["update"]
}

# --- Policy: decision-emitter ---
path "kv/data/fraud-detection-pipeline/decision-emitter/*" {
  capabilities = ["read", "list"]
}

path "pki/fraud-detection-pipeline/issue/decision-emitter" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/fraud-detection-pipeline" {
  capabilities = ["update"]
}
path "transit/decrypt/fraud-detection-pipeline" {
  capabilities = ["update"]
}
