"""Unit tests for the HCL syntax validator."""

from pathlib import Path

from click.testing import CliRunner

from calm_forge.cli import cli
from calm_forge.hcl_validator import validate_hcl_syntax

EXAMPLES_DIR = Path(__file__).parent.parent / "examples"


# ---------------------------------------------------------------------------
# Valid HCL cases
# ---------------------------------------------------------------------------


def test_valid_empty_block():
    hcl = 'component "web" "frontend" {\n}\n'
    assert validate_hcl_syntax(hcl) == []


def test_valid_nested_blocks():
    hcl = """
required_providers {
  kubernetes = {
    source  = "hashicorp/kubernetes"
    version = "~> 2.30"
  }
}
"""
    assert validate_hcl_syntax(hcl) == []


def test_valid_attributes():
    hcl = 'address = "https://vault.example.com"\ntoken   = var.vault_token\n'
    assert validate_hcl_syntax(hcl) == []


def test_valid_multiline_nested():
    hcl = """
provider "vault" "this" {
  address = var.vault_addr
  token   = var.vault_token
}

component "app" "api" {
  source  = "./modules/k8s-deployment"
  version = "~> 1.0"

  inputs = {
    namespace = var.namespace
    image     = var.api_image
  }
}
"""
    assert validate_hcl_syntax(hcl) == []


# ---------------------------------------------------------------------------
# Unbalanced brace cases
# ---------------------------------------------------------------------------


def test_unbalanced_open_brace():
    hcl = 'component "web" {\n  inputs = {\n'
    errors = validate_hcl_syntax(hcl)
    assert len(errors) == 1
    assert "never closed" in errors[0]


def test_unbalanced_close_brace():
    hcl = 'component "web" {\n}\n}\n'
    errors = validate_hcl_syntax(hcl)
    assert len(errors) == 1
    assert "unexpected" in errors[0].lower() or "closing" in errors[0].lower()


# ---------------------------------------------------------------------------
# Unterminated string
# ---------------------------------------------------------------------------


def test_unterminated_string_newline():
    hcl = 'address = "https://vault.example.com\ntoken = var.vault_token\n'
    errors = validate_hcl_syntax(hcl)
    assert any("unterminated string" in e for e in errors)


def test_unterminated_string_eof():
    hcl = 'address = "https://vault.example.com'
    errors = validate_hcl_syntax(hcl)
    assert any("unterminated string" in e for e in errors)


# ---------------------------------------------------------------------------
# Braces inside strings are ignored
# ---------------------------------------------------------------------------


def test_brace_inside_string_ignored():
    hcl = 'label = "hello { world }"\n'
    assert validate_hcl_syntax(hcl) == []


def test_brace_inside_string_does_not_affect_depth():
    hcl = 'component "x" {\n  label = "{ not a block }"\n}\n'
    assert validate_hcl_syntax(hcl) == []


# ---------------------------------------------------------------------------
# Braces inside comments are ignored
# ---------------------------------------------------------------------------


def test_brace_inside_line_comment_hash():
    hcl = "# this is { a comment }\ncomponent \"x\" {\n}\n"
    assert validate_hcl_syntax(hcl) == []


def test_brace_inside_line_comment_slash():
    hcl = '// this is { a comment }\ncomponent "x" {\n}\n'
    assert validate_hcl_syntax(hcl) == []


def test_brace_inside_block_comment():
    hcl = '/* open { and close } */\ncomponent "x" {\n}\n'
    assert validate_hcl_syntax(hcl) == []


def test_unterminated_block_comment():
    hcl = '/* this comment never ends\ncomponent "x" {\n}\n'
    errors = validate_hcl_syntax(hcl)
    assert any("block comment" in e for e in errors)


# ---------------------------------------------------------------------------
# Realistic generated snippet
# ---------------------------------------------------------------------------


def test_realistic_components_snippet():
    hcl = """# ============================================================
# GENERATED BY: CALM Forge v0.1
# DO NOT EDIT — regenerate from CALM source
# ============================================================

required_providers {
  kubernetes = {
    source  = "hashicorp/kubernetes"
    version = "~> 2.30"
  }
  vault = {
    source  = "hashicorp/vault"
    version = "~> 4.2"
  }
}

provider "kubernetes" "ocp" {
  config_path = var.kubeconfig_path
}

provider "vault" "this" {
  address = var.vault_addr
  token   = var.vault_token
}

component "service" "web_frontend" {
  source  = "./modules/k8s-deployment"
  version = "~> 1.0"

  inputs = {
    namespace       = var.namespace
    vault_pki_path  = component.vault_pki_mtls.outputs.pki_path
  }
}
"""
    assert validate_hcl_syntax(hcl) == []


# ---------------------------------------------------------------------------
# Integration tests: --validate flag on the CLI
# ---------------------------------------------------------------------------


def test_cli_generate_validate_flag_passes(tmp_path):
    """generate --validate on fsi-3tier exits 0 and prints success message."""
    ex = EXAMPLES_DIR / "fsi-3tier"
    result = CliRunner().invoke(cli, [
        "generate",
        "--calm", str(ex / "instantiation.json"),
        "--decorator", str(ex / "decorator.json"),
        "--catalog", str(ex / "catalog.json"),
        "--output-dir", str(tmp_path),
        "--validate",
    ])
    assert result.exit_code == 0, result.output
    assert "validation passed" in result.output


def test_cli_validate_flag_reports_file_count(tmp_path):
    """generate --validate reports correct number of HCL files validated."""
    ex = EXAMPLES_DIR / "fsi-3tier"
    result = CliRunner().invoke(cli, [
        "generate",
        "--calm", str(ex / "instantiation.json"),
        "--decorator", str(ex / "decorator.json"),
        "--catalog", str(ex / "catalog.json"),
        "--output-dir", str(tmp_path),
        "--validate",
    ])
    assert result.exit_code == 0, result.output
    # Default generate produces 3 HCL files
    assert "3 files OK" in result.output


def test_cli_validate_flag_all_examples_pass(tmp_path):
    """generate --validate exits 0 for all FSI examples."""
    all_examples = [
        "fsi-3tier",
        "fsi-event-driven",
        "fsi-microservices-mesh",
        "fsi-mongodb-multiregion",
    ]
    for example in all_examples:
        ex = EXAMPLES_DIR / example
        out = tmp_path / example
        result = CliRunner().invoke(cli, [
            "generate",
            "--calm", str(ex / "instantiation.json"),
            "--decorator", str(ex / "decorator.json"),
            "--catalog", str(ex / "catalog.json"),
            "--output-dir", str(out),
            "--validate",
        ])
        assert result.exit_code == 0, f"{example}: {result.output}"
        assert "validation passed" in result.output, f"{example}: missing success message"
