# ============================================================
# GENERATED BY: CALM Forge v0.1
# SOURCE:       digital-banking-platform.architecture.json
# PATTERN:      fsi-microservices-mesh.pattern.json
# DO NOT EDIT — regenerate from CALM source
# ============================================================

required_providers {
  kubernetes = {
    source  = "hashicorp/kubernetes"
    version = "~> 2.30"
  }
  vault = {
    source  = "hashicorp/vault"
    version = "~> 4.2"
  }
  helm = {
    source  = "hashicorp/helm"
    version = "~> 2.13"
  }
}

provider "kubernetes" "ocp" {
  config_path = var.kubeconfig_path
}

provider "vault" "this" {
  address = var.vault_addr
  token   = var.vault_token
}

provider "helm" "this" {
  kubernetes {
    config_path = var.kubeconfig_path
  }
}

# --- Component: api-gateway ---
# CALM node: api-gateway (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "api_gateway" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "api-gateway"
    namespace        = var.namespace
    container_image  = "registry.internal/digital-banking/api-gateway:2.4.0"
    replicas         = 4
    cpu_request      = "1000m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "api-gateway"
    service_mesh     = true
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: account-service ---
# CALM node: account-service (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "account_service" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "account-service"
    namespace        = var.namespace
    container_image  = "registry.internal/digital-banking/account-service:1.8.3"
    replicas         = 3
    cpu_request      = "500m"
    memory_request   = "512Mi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "account-service"
    service_mesh     = true
    db_connection    = component.postgres_accounts.outputs.connection_string
    db_vault_path    = component.vault_dynamic_db_creds.outputs.creds_path
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: payment-service ---
# CALM node: payment-service (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "payment_service" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "payment-service"
    namespace        = var.namespace
    container_image  = "registry.internal/digital-banking/payment-service:1.6.1"
    replicas         = 3
    cpu_request      = "1000m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "payment-service"
    service_mesh     = true
    db_connection    = component.postgres_payments.outputs.connection_string
    db_vault_path    = component.vault_dynamic_db_creds.outputs.creds_path
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: notification-service ---
# CALM node: notification-service (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "notification_service" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "notification-service"
    namespace        = var.namespace
    container_image  = "registry.internal/digital-banking/notification-service:1.3.0"
    replicas         = 2
    cpu_request      = "250m"
    memory_request   = "256Mi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "notification-service"
    service_mesh     = true
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: fraud-detection ---
# CALM node: fraud-detection (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "fraud_detection" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "fraud-detection"
    namespace        = var.namespace
    container_image  = "registry.internal/digital-banking/fraud-detection:2.1.0"
    replicas         = 3
    cpu_request      = "2000m"
    memory_request   = "4Gi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "fraud-detection"
    service_mesh     = true
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: auth-service ---
# CALM node: auth-service (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "auth_service" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "auth-service"
    namespace        = var.namespace
    container_image  = "registry.internal/digital-banking/auth-service:1.5.2"
    replicas         = 3
    cpu_request      = "500m"
    memory_request   = "512Mi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "auth-service"
    service_mesh     = true
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: redis-cache ---
# CALM node: redis-cache (cache, engine=redis)
# Module: registry.terraform.io/uhccp/redis-sentinel-ocp/v1.0.0
component "redis_cache" {
  source = "registry.terraform.io/uhccp/redis-sentinel-ocp/v1.0.0"

  inputs = {
  }

  providers = {
  }
}

# --- Component: postgres-accounts ---
# CALM node: postgres-accounts (database, engine=postgresql)
# Module: registry.terraform.io/uhccp/crunchydata-postgres/v1.3.0
component "postgres_accounts" {
  source = "registry.terraform.io/uhccp/crunchydata-postgres/v1.3.0"

  inputs = {
    name           = "digital-banking-platform-db"
    namespace      = var.namespace
    version        = "15.4"
    storage_class  = "encrypted-ssd"
    storage_size   = "200Gi"
    vault_addr     = var.vault_addr
    encryption_key = var.vault_transit_key
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
    helm       = provider.helm.this
  }
}

# --- Component: postgres-payments ---
# CALM node: postgres-payments (database, engine=postgresql)
# Module: registry.terraform.io/uhccp/crunchydata-postgres/v1.3.0
component "postgres_payments" {
  source = "registry.terraform.io/uhccp/crunchydata-postgres/v1.3.0"

  inputs = {
    name           = "digital-banking-platform-db"
    namespace      = var.namespace
    version        = "15.4"
    storage_class  = "encrypted-ssd"
    storage_size   = "500Gi"
    vault_addr     = var.vault_addr
    encryption_key = var.vault_transit_key
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
    helm       = provider.helm.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: gateway-to-account (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/digital-banking-platform"
    allowed_domains   = ["api-gateway.${var.namespace}.svc", "account-service.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: gateway-to-payment (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/digital-banking-platform"
    allowed_domains   = ["api-gateway.${var.namespace}.svc", "payment-service.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: gateway-to-auth (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/digital-banking-platform"
    allowed_domains   = ["api-gateway.${var.namespace}.svc", "auth-service.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-dynamic-db-creds ---
# CALM relationship: account-to-db (authentication=vault-dynamic-credentials)
# Module: registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0
component "vault_dynamic_db_creds" {
  source = "registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0"

  inputs = {
    db_mount_path     = "database/digital-banking-platform"
    db_connection_url = component.postgres_accounts.outputs.connection_string
    allowed_roles     = ["account-service"]
    default_ttl       = "1h"
    max_ttl           = "24h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-dynamic-db-creds ---
# CALM relationship: payment-to-db (authentication=vault-dynamic-credentials)
# Module: registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0
component "vault_dynamic_db_creds" {
  source = "registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0"

  inputs = {
    db_mount_path     = "database/digital-banking-platform"
    db_connection_url = component.postgres_payments.outputs.connection_string
    allowed_roles     = ["payment-service"]
    default_ttl       = "1h"
    max_ttl           = "24h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: payment-to-fraud (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/digital-banking-platform"
    allowed_domains   = ["payment-service.${var.namespace}.svc", "fraud-detection.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: payment-to-notification (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/digital-banking-platform"
    allowed_domains   = ["payment-service.${var.namespace}.svc", "notification-service.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-kv-creds ---
# CALM relationship: auth-to-redis (authentication=vault-kv-credentials)
# Module: registry.terraform.io/uhccp/vault-kv-creds/v1.0.0
component "vault_kv_creds" {
  source = "registry.terraform.io/uhccp/vault-kv-creds/v1.0.0"

  inputs = {
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-kv-creds ---
# CALM relationship: fraud-to-redis (authentication=vault-kv-credentials)
# Module: registry.terraform.io/uhccp/vault-kv-creds/v1.0.0
component "vault_kv_creds" {
  source = "registry.terraform.io/uhccp/vault-kv-creds/v1.0.0"

  inputs = {
  }

  providers = {
    vault = provider.vault.this
  }
}
