# ============================================================
# GENERATED BY: CALM Forge v0.1
# SOURCE:       trade-pipeline.architecture.json
# PATTERN:      fsi-event-driven.pattern.json
# GENERATED:    (timestamp varies)
# DO NOT EDIT — regenerate from CALM source
# ============================================================

required_providers {
  kubernetes = {
    source  = "hashicorp/kubernetes"
    version = "~> 2.30"
  }
  vault = {
    source  = "hashicorp/vault"
    version = "~> 4.2"
  }
  helm = {
    source  = "hashicorp/helm"
    version = "~> 2.13"
  }
}

provider "kubernetes" "ocp" {
  config_path = var.kubeconfig_path
}

provider "vault" "this" {
  address = var.vault_addr
  token   = var.vault_token
}

provider "helm" "this" {
  kubernetes {
    config_path = var.kubeconfig_path
  }
}

# --- Component: order-intake ---
# CALM node: order-intake (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "order_intake" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "order-intake"
    namespace        = var.namespace
    container_image  = "registry.internal/trading/order-intake:2.4.0"
    replicas         = 3
    cpu_request      = "500m"
    memory_request   = "512Mi"
    port             = 8443
    protocol         = "HTTPS"
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: kafka-cluster ---
# CALM node: kafka-cluster (kafka)
# Module: registry.terraform.io/uhccp/kafka-cluster-ocp/v1.2.0
component "kafka_cluster" {
  source = "registry.terraform.io/uhccp/kafka-cluster-ocp/v1.2.0"

  inputs = {
  }

  providers = {
  }
}

# --- Component: trade-processor ---
# CALM node: trade-processor (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "trade_processor" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "trade-processor"
    namespace        = var.namespace
    container_image  = "registry.internal/trading/trade-processor:2.4.0"
    replicas         = 5
    cpu_request      = "2000m"
    memory_request   = "2Gi"
    port             = 8443
    protocol         = "HTTPS"
    db_connection    = component.postgres_db.outputs.connection_string
    db_vault_path    = component.vault_dynamic_db_creds.outputs.creds_path
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: settlement-engine ---
# CALM node: settlement-engine (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "settlement_engine" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "settlement-engine"
    namespace        = var.namespace
    container_image  = "registry.internal/trading/settlement-engine:2.4.0"
    replicas         = 3
    cpu_request      = "1000m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
    db_connection    = component.postgres_db.outputs.connection_string
    db_vault_path    = component.vault_dynamic_db_creds.outputs.creds_path
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: audit-logger ---
# CALM node: audit-logger (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "audit_logger" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "audit-logger"
    namespace        = var.namespace
    container_image  = "registry.internal/trading/audit-logger:2.4.0"
    replicas         = 3
    cpu_request      = "500m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: postgres-db ---
# CALM node: postgres-db (database, engine=postgresql)
# Module: registry.terraform.io/uhccp/crunchydata-postgres/v1.3.0
component "postgres_db" {
  source = "registry.terraform.io/uhccp/crunchydata-postgres/v1.3.0"

  inputs = {
    name           = "trade-pipeline-db"
    namespace      = var.namespace
    version        = "15.4"
    storage_class  = "encrypted-ssd"
    storage_size   = "200Gi"
    vault_addr     = var.vault_addr
    encryption_key = var.vault_transit_key
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
    helm       = provider.helm.this
  }
}

# --- Component: vault-kv-kafka-sasl ---
# CALM relationship: order-intake-produces-orders (authentication=vault-kafka-sasl-scram)
# Module: registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0
component "vault_kv_kafka_sasl" {
  source = "registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0"

  inputs = {
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-kv-kafka-sasl ---
# CALM relationship: kafka-to-trade-processor (authentication=vault-kafka-sasl-scram)
# Module: registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0
component "vault_kv_kafka_sasl" {
  source = "registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0"

  inputs = {
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-kv-kafka-sasl ---
# CALM relationship: trade-processor-produces-processed (authentication=vault-kafka-sasl-scram)
# Module: registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0
component "vault_kv_kafka_sasl" {
  source = "registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0"

  inputs = {
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-kv-kafka-sasl ---
# CALM relationship: kafka-to-settlement-engine (authentication=vault-kafka-sasl-scram)
# Module: registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0
component "vault_kv_kafka_sasl" {
  source = "registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0"

  inputs = {
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-kv-kafka-sasl ---
# CALM relationship: kafka-to-audit-logger (authentication=vault-kafka-sasl-scram)
# Module: registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0
component "vault_kv_kafka_sasl" {
  source = "registry.terraform.io/uhccp/vault-kv-kafka-sasl/v1.0.0"

  inputs = {
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-dynamic-db-creds ---
# CALM relationship: trade-processor-to-db (authentication=vault-dynamic-credentials)
# Module: registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0
component "vault_dynamic_db_creds" {
  source = "registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0"

  inputs = {
    db_mount_path     = "database/trade-pipeline"
    db_connection_url = component.postgres_db.outputs.connection_string
    allowed_roles     = ["trade-processor"]
    default_ttl       = "1h"
    max_ttl           = "24h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-dynamic-db-creds ---
# CALM relationship: settlement-engine-to-db (authentication=vault-dynamic-credentials)
# Module: registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0
component "vault_dynamic_db_creds" {
  source = "registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0"

  inputs = {
    db_mount_path     = "database/trade-pipeline"
    db_connection_url = component.postgres_db.outputs.connection_string
    allowed_roles     = ["settlement-engine"]
    default_ttl       = "1h"
    max_ttl           = "24h"
  }

  providers = {
    vault = provider.vault.this
  }
}
