"""Ansible YAML generation — inventory and EDA rulebooks from CALM."""

import yaml


def _header_comment(title):
    return (
        "# ============================================================\n"
        "# GENERATED BY: CALM Forge v0.2\n"
        f"# {title}\n"
        "# DO NOT EDIT — regenerate from CALM source\n"
        "# ============================================================\n"
    )


def write_inventory(component_map, decorators, metadata):
    """Generate ansible/inventory.yml — dynamic inventory from CALM nodes.

    Groups by node type (services, databases, middleware).
    Host vars from node properties, group vars from decorator.
    """
    app_name = metadata.get("application-name", "app")
    decorator = decorators[0] if decorators else {}
    dec_data = decorator.get("data", {})
    k8s = dec_data.get("kubernetes", {})
    environment = dec_data.get("environment", "production")
    region = dec_data.get("region", "default")
    cluster = k8s.get("cluster", "default")
    namespace = k8s.get("namespace", app_name)

    # Classify nodes into groups
    groups = {}
    type_to_group = {
        "service": "services",
        "database": "databases",
    }

    for node_id, entry in component_map.items():
        node = entry["node"]
        node_type = node["node-type"]
        if node_type == "system":
            continue

        group_name = type_to_group.get(node_type, "other")
        if group_name not in groups:
            groups[group_name] = {}

        host_vars = {"ansible_host": f"{node_id}.{namespace}.svc"}

        if node_type == "service":
            host_vars["container_image"] = node.get("container-image", "")
            host_vars["replicas"] = node.get("replicas", 1)
            host_vars["cpu_request"] = node.get("cpu-request", "500m")
            host_vars["memory_request"] = node.get("memory-request", "512Mi")
        elif node_type == "database":
            host_vars["engine"] = node.get("engine", "")
            host_vars["version"] = node.get("version", "")
            host_vars["storage_class"] = node.get("storage-class", "")
            host_vars["storage_size"] = node.get("storage-size", "")

        groups[group_name][node_id] = host_vars

    # Build inventory structure
    inventory = {
        "all": {
            "vars": {
                "application_name": app_name,
                "environment": environment,
                "region": region,
                "cluster": cluster,
                "namespace": namespace,
                "vault_addr": f"https://vault.{environment}.{region}.uhccp.internal:8200",
                "vault_namespace": f"{app_name}/{environment}",
                "vault_auth_method": "approle",
            },
            "children": {},
        }
    }

    for group_name, hosts in sorted(groups.items()):
        inventory["all"]["children"][group_name] = {
            "hosts": hosts,
        }

    header = _header_comment(f"Ansible inventory for {app_name}")
    body = yaml.dump(inventory, default_flow_style=False, sort_keys=False)
    return header + body


def write_eda_rulebook(component_map, rel_components, metadata, drift_event_file=None):
    """Generate ansible/eda-rulebook.yml — Event-Driven Ansible rules for Day 2.

    - Service nodes → config drift remediation + agent restore rules
    - Database nodes → connection pool monitoring
    - mTLS relationships → certificate auto-renewal (Vault PKI event source)
    - vault-dynamic-credentials → credential rotation monitoring
    - drift_event_file → calm.drift.evaluated file-watcher source + violation rule
    """
    app_name = metadata.get("application-name", "app")

    rules = []

    # Service node rules
    for node_id, entry in component_map.items():
        node = entry["node"]
        node_type = node["node-type"]

        if node_type == "service":
            rules.append({
                "name": f"{node_id} config drift remediation",
                "condition": (
                    f'event.payload.alert_type == "configuration_drift" and '
                    f'event.payload.entity_id == "{node_id}"'
                ),
                "action": {
                    "run_job_template": {
                        "name": "day2-drift-remediation",
                        "organization": "UHCCP",
                        "job_args": {
                            "extra_vars": {
                                "target_service": node_id,
                                "application": app_name,
                            },
                        },
                    },
                },
            })
            rules.append({
                "name": f"{node_id} agent health restore",
                "condition": (
                    f'event.payload.alert_type == "agent_unhealthy" and '
                    f'event.payload.entity_id == "{node_id}"'
                ),
                "action": {
                    "run_job_template": {
                        "name": "day2-agent-restore",
                        "organization": "UHCCP",
                        "job_args": {
                            "extra_vars": {
                                "target_service": node_id,
                                "application": app_name,
                            },
                        },
                    },
                },
            })

        elif node_type == "database":
            rules.append({
                "name": f"{node_id} connection pool monitoring",
                "condition": (
                    f'event.payload.alert_type == "connection_pool_exhaustion" and '
                    f'event.payload.entity_id == "{node_id}"'
                ),
                "action": {
                    "run_job_template": {
                        "name": "day2-db-connection-remediation",
                        "organization": "UHCCP",
                        "job_args": {
                            "extra_vars": {
                                "target_database": node_id,
                                "application": app_name,
                            },
                        },
                    },
                },
            })

    # Relationship-derived rules
    for rc in rel_components:
        rel = rc["relationship"]
        auth = rel.get("authentication", "")
        connects = rel["relationship-type"]["connects"]
        src = connects.get("source", {}).get("node", "")
        dst = connects.get("destination", {}).get("node", "")

        if auth == "mTLS-vault-pki":
            rules.append({
                "name": f"Certificate auto-renewal ({src} ↔ {dst} mTLS)",
                "condition": (
                    f'event.payload.source == "vault" and '
                    f'event.payload.event_type == "cert_expiring" and '
                    f'event.payload.cert_path starts_with "pki/{app_name}"'
                ),
                "action": {
                    "run_job_template": {
                        "name": "cert-rotation-vault-pki",
                        "organization": "UHCCP",
                        "job_args": {
                            "extra_vars": {
                                "pki_mount": f"pki/{app_name}",
                                "application": app_name,
                            },
                        },
                    },
                },
            })

        elif auth == "vault-dynamic-credentials":
            rules.append({
                "name": f"Credential rotation monitoring ({src} → {dst})",
                "condition": (
                    f'event.payload.source == "vault" and '
                    f'event.payload.event_type == "lease_expiring" and '
                    f'event.payload.mount_path == "database/{app_name}"'
                ),
                "action": {
                    "run_job_template": {
                        "name": "credential-rotation-monitor",
                        "organization": "UHCCP",
                        "job_args": {
                            "extra_vars": {
                                "db_mount": f"database/{app_name}",
                                "consumer_service": src,
                                "application": app_name,
                            },
                        },
                    },
                },
            })

    sources = [
        {
            "ansible.eda.webhook": {
                "host": "0.0.0.0",
                "port": 5000,
            },
        },
    ]

    if drift_event_file:
        sources.append({
            "ansible.eda.file_watcher": {
                "path": str(drift_event_file),
            },
        })
        rules.append({
            "name": "Respond to calm drift violation",
            "condition": 'event.calm.drift.status == "violation"',
            "action": {
                "run_playbook": {
                    "name": "drift-remediation.yml",
                    "extra_vars": {
                        "workload": "{{ event.calm.drift.workload }}",
                        "findings": "{{ event.calm.drift.findings }}",
                    },
                },
            },
        })

    rulebook = [
        {
            "name": f"{app_name} Day 2 Operations",
            "hosts": "all",
            "sources": sources,
            "rules": rules,
        }
    ]

    header = _header_comment(f"EDA rulebook for {app_name}")
    body = yaml.dump(rulebook, default_flow_style=False, sort_keys=False, allow_unicode=True)
    return header + body
