"""Backstage / Red Hat DevHub entity provider.

Reads a live KG directory and emits Backstage Software Catalog YAML entities:
  ExecutionEnvironment → kind: Resource  (kubernetes-cluster)
  Workload             → kind: Component (service)
  Placement            → folds into Component as dependsOn + calm.io/ annotations

All entities use the calm.io/ annotation namespace so they are identifiable
and filterable in the catalog without colliding with existing annotations.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_catalog(kg_dir: Path) -> list[dict[str, Any]]:
    """Read a live KG directory and return a list of Backstage catalog entities.

    The list is ordered: Resources (clusters) first, then Components (workloads).
    """
    environments = _load_nodes(kg_dir / "environments", "ExecutionEnvironment")
    workloads    = _load_nodes(kg_dir / "workloads",    "Workload")
    placements   = _load_nodes(kg_dir / "placements",   "Placement")

    entities: list[dict[str, Any]] = []
    for env in environments:
        entities.append(env_to_resource(env))
    for wl in workloads:
        wl_placements = [
            p for p in placements
            if p.get("workload_id") == wl.get("@id")
        ]
        entities.append(workload_to_component(wl, wl_placements))

    return entities


def write_catalog(entities: list[dict[str, Any]], output_dir: Path) -> Path:
    """Serialise entities to <output_dir>/catalog-info.yaml."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "catalog-info.yaml"
    path.write_text(to_catalog_yaml(entities))
    return path


def to_catalog_yaml(entities: list[dict[str, Any]]) -> str:
    """Serialise a list of Backstage entities to multi-document YAML."""
    header = (
        "# Generated by calm-forge backstage\n"
        "# calm.io/ annotation namespace — do not edit manually\n"
    )
    docs = [
        yaml.dump(e, default_flow_style=False, sort_keys=False, allow_unicode=True).strip()
        for e in entities
    ]
    return header + "\n---\n".join(docs) + "\n"


# ---------------------------------------------------------------------------
# Entity builders
# ---------------------------------------------------------------------------

def env_to_resource(node: dict[str, Any]) -> dict[str, Any]:
    """ExecutionEnvironment KG node → Backstage Resource (kubernetes-cluster)."""
    name = _bs_name(node.get("@id", "").replace("env:acm:", ""))
    caps = node.get("advertised_capabilities", [])
    status = node.get("status", "unknown")
    region = node.get("region", "")
    labels = node.get("labels", {})

    annotations: dict[str, str] = {
        "calm.io/environment-id": node.get("@id", ""),
        "calm.io/cluster-status": status,
        "calm.io/region": region,
    }
    if caps:
        annotations["calm.io/advertised-capabilities"] = ",".join(sorted(caps))
    if labels:
        for k, v in labels.items():
            annotations[f"calm.io/label-{k}"] = str(v)

    return {
        "apiVersion": "backstage.io/v1alpha1",
        "kind": "Resource",
        "metadata": {
            "name": name,
            "annotations": annotations,
        },
        "spec": {
            "type": "kubernetes-cluster",
            "lifecycle": "production" if status == "ready" else "experimental",
            "owner": "group:platform-engineering",
        },
    }


def workload_to_component(
    node: dict[str, Any],
    placements: list[dict[str, Any]],
) -> dict[str, Any]:
    """Workload KG node + its Placements → Backstage Component (service)."""
    wl_id = node.get("@id", "")
    name = _bs_name(wl_id.replace("workload:", ""))
    owner = node.get("owner", "platform-engineering")
    if not owner.startswith("group:") and not owner.startswith("user:"):
        owner = f"group:{owner}"

    prov = node.get("_provenance", {}).get("provenance", "")
    lifecycle = "production" if prov == "authored" else "experimental"

    caps = node.get("declared_capabilities", [])
    # Collect from component nodes if flat list is empty
    if not caps:
        for comp in node.get("nodes", []):
            caps = list(set(caps) | set(comp.get("declared_capabilities", [])))
        caps = sorted(caps)

    compliance = node.get("compliance_scope", [])

    annotations: dict[str, str] = {
        "calm.io/workload-id": wl_id,
        "calm.io/provenance": prov or "unknown",
    }
    if caps:
        annotations["calm.io/capabilities-declared"] = ",".join(sorted(caps))
    if compliance:
        annotations["calm.io/compliance-scope"] = ",".join(compliance)
    if node.get("review_required"):
        annotations["calm.io/review-required"] = "true"

    # Aggregate drift state across placements
    drift_statuses = [
        p.get("drift_state", {}).get("status", "unknown")
        for p in placements
    ]
    if drift_statuses:
        overall = _aggregate_drift(drift_statuses)
        annotations["calm.io/drift-status"] = overall
        last_ts = max(
            (p.get("drift_state", {}).get("last_evaluated") or "")
            for p in placements
        )
        if last_ts:
            annotations["calm.io/last-evaluated"] = last_ts
        # Capability grants from manifests_as edges
        granted: set[str] = set()
        for p in placements:
            for edge in p.get("edges", []):
                if edge.get("@type") == "manifests_as":
                    granted.update(edge.get("capabilities_granted", []))
        if granted:
            annotations["calm.io/capabilities-granted"] = ",".join(sorted(granted))

    # dependsOn: one entry per placed cluster
    depends_on: list[str] = []
    for p in placements:
        env_id = p.get("environment_id", "")
        cluster = _bs_name(env_id.replace("env:acm:", ""))
        ref = f"resource:{cluster}"
        if ref not in depends_on:
            depends_on.append(ref)

    spec: dict[str, Any] = {
        "type": "service",
        "lifecycle": lifecycle,
        "owner": owner,
    }
    if depends_on:
        spec["dependsOn"] = depends_on

    return {
        "apiVersion": "backstage.io/v1alpha1",
        "kind": "Component",
        "metadata": {
            "name": name,
            "annotations": annotations,
        },
        "spec": spec,
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _bs_name(raw: str) -> str:
    """Sanitise a string to a valid Backstage entity name (DNS subdomain)."""
    return re.sub(r"[^a-z0-9-]", "-", raw.lower()).strip("-")[:63]


def _aggregate_drift(statuses: list[str]) -> str:
    if "violation" in statuses:
        return "violation"
    if all(s == "ok" for s in statuses):
        return "ok"
    if all(s == "pending_first_evaluation" for s in statuses):
        return "pending_first_evaluation"
    return "mixed"


def _load_nodes(directory: Path, type_val: str) -> list[dict[str, Any]]:
    if not directory.exists():
        return []
    nodes = []
    for path in sorted(directory.glob("*.json")):
        try:
            node = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        if node.get("@type") == type_val:
            nodes.append(node)
    return nodes
