"""Compile CALM Forge KG Policy predicate nodes to OPA Rego rules.

Evaluation contexts
-------------------
Not all predicate types are evaluable at pre-generation time. The pre-generation
gate only has access to the CALM spec + decorator. Some predicates need the
Placement node (diff engine) or runtime Agent state (manifests_as boundary).

  PRE_GENERATION  placement_constraint, compliance_boundary
                  Evaluable at intent authoring time. Compiled to calm.violations.

  DRIFT_ENGINE    drift_threshold, lifecycle_condition
                  Evaluated by the diff engine on a schedule. Not compiled here.

  RUNTIME         capability_ceiling, isolation_requirement, capability_requirement
                  Require runtime context (Placement, co-residents, environment
                  capabilities). Compiled to calm.drift (stub — Phase 1 scope).
                  Full implementation deferred to diff engine integration.
"""
from __future__ import annotations

import json
from typing import Any

PRE_GENERATION = {"placement_constraint", "compliance_boundary"}
DRIFT_ENGINE = {"drift_threshold", "lifecycle_condition"}
RUNTIME = {"capability_ceiling", "isolation_requirement", "capability_requirement"}

_REGO_HEADER = """\
# AUTO-GENERATED by calm_forge.kg_compiler — do not edit by hand.
# Source: knowledge graph Policy predicate nodes (ADR-004).
# Regenerate: calm-forge compile-policies
package calm

import rego.v1

"""

_VIOLATIONS_ARRAY = """
# violations: array form (primary query target for opa eval)
violations := [v | v := violation[_]]
"""

_DRIFT_HEADER = """\
# AUTO-GENERATED by calm_forge.kg_compiler — do not edit by hand.
# Post-placement drift evaluation — evaluates a Placement node against Workload intent.
# Input: { "workload": <Workload node>, "placement": <Placement node>, "policies": [...] }
# Query: data.calm.drift.drift_violations
package calm.drift

import rego.v1

"""

_DRIFT_CAPABILITY_CEILING = """\
# capability_ceiling: observed_capabilities must be subset of declared_capabilities.
# Fires if a placement grants capabilities beyond what the workload declared.
drift_violation contains v if {
    cap := input.placement.observed_capabilities[_]
    not cap in input.workload.declared_capabilities
    v := {
        "rule": "capability-ceiling",
        "severity": "error",
        "message": sprintf(
            "Capability '%v' observed in placement but not declared in workload intent '%v'",
            [cap, input.workload["@id"]],
        ),
    }
}

"""

_DRIFT_THRESHOLD = """\
# drift_threshold: flag if placement deviation exceeds the declared maximum.
# Requires placement.drift_state.deviation_hours to be populated by the diff engine.
drift_violation contains v if {
    pol := input.policies[_]
    pol.predicate_type == "drift_threshold"
    deviation := input.placement.drift_state.deviation_hours
    deviation != null
    deviation > pol.max_deviation_hours
    v := {
        "rule": pol["@id"],
        "severity": _drift_severity(pol),
        "message": sprintf(
            "Drift threshold exceeded: %v hours > declared max %v hours",
            [deviation, pol.max_deviation_hours],
        ),
    }
}

_drift_severity(pol) := "error" if pol.enforcement_mode == "enforce"

_drift_severity(pol) := "warning" if pol.enforcement_mode != "enforce"

"""

_DRIFT_FOOTER = """\
drift_violations := [v | v := drift_violation[_]]
"""


# ---------------------------------------------------------------------------
# Public
# ---------------------------------------------------------------------------


def compile_violations(policies: list[dict[str, Any]]) -> str:
    """Compile pre-generation Policy predicate nodes to calm.violations Rego."""
    rules: list[str] = []

    for policy in policies:
        predicate_type = policy.get("predicate_type", "")
        enforcement = policy.get("enforcement_mode", "enforce")

        if predicate_type == "placement_constraint":
            rule = _compile_placement_constraint(policy, enforcement)
        elif predicate_type == "compliance_boundary":
            rule = _compile_compliance_boundary(policy, enforcement)
        else:
            # Not evaluable at pre-generation time — emit a comment only
            pid = policy.get("@id", "unknown")
            rule = (
                f"# Predicate '{predicate_type}' on {pid}\n"
                f"# Evaluation context: {_context_label(predicate_type)} — not compiled to calm.violations\n"
            )

        rules.append(rule)

    return _REGO_HEADER + "\n".join(rules) + _VIOLATIONS_ARRAY


def compile_drift(policies: list[dict[str, Any]] | None = None) -> str:
    """Compile the calm.drift package.

    Generates rules for drift_threshold predicates found in policies.
    Always includes the capability_ceiling rule (invariant from ADR-004).
    """
    # drift_threshold rules are data-driven from the policy list at evaluation time
    # (the Rego iterates input.policies), so we don't need per-policy templates.
    # The rules are fixed; the data varies per evaluation call.
    return _DRIFT_HEADER + _DRIFT_CAPABILITY_CEILING + _DRIFT_THRESHOLD + _DRIFT_FOOTER


def compile_all(policies: list[dict[str, Any]]) -> dict[str, str]:
    """Compile policies to a bundle: {'calm_violations.rego': ..., 'calm_drift.rego': ...}."""
    return {
        "calm_violations.rego": compile_violations(policies),
        "calm_drift.rego": compile_drift(policies),
    }


# ---------------------------------------------------------------------------
# Predicate compilers
# ---------------------------------------------------------------------------


def _compile_placement_constraint(policy: dict[str, Any], enforcement: str) -> str:
    """Generate a Rego rule for a placement_constraint predicate."""
    pid = policy.get("@id", "unknown")
    required_labels: dict[str, str] = policy.get("required_labels", {})
    rationale = policy.get("rationale", "Placement constraint violated")
    severity = "error" if enforcement == "enforce" else "warning"

    if not required_labels:
        return f"# placement_constraint {pid}: no required_labels — skipped\n"

    checks: list[str] = []
    msg_parts: list[str] = []

    for key, expected in required_labels.items():
        checks.append(f'    input.decorator.data["{key}"] != "{expected}"')
        msg_parts.append(f"{key}={expected}")

    checks_str = "\n".join(checks)
    expected_desc = ", ".join(msg_parts)
    rule_id = _safe_rule_id(pid)

    return f"""\
# {pid}
# {rationale}
violation contains v if {{
{checks_str}
    v := {{
        "rule": "{rule_id}",
        "severity": "{severity}",
        "message": sprintf("Placement constraint: requires {expected_desc}. Got: %v", [json.marshal(input.decorator.data)]),
    }}
}}

"""


def _compile_compliance_boundary(policy: dict[str, Any], enforcement: str) -> str:
    """Generate a Rego rule for a compliance_boundary predicate."""
    pid = policy.get("@id", "unknown")
    allowed_regions: list[str] = policy.get("allowed_regions", [])
    rationale = policy.get("rationale", "Compliance boundary violated")
    severity = "error" if enforcement == "enforce" else "warning"

    if not allowed_regions:
        return f"# compliance_boundary {pid}: no allowed_regions — skipped\n"

    regions_rego = json.dumps(allowed_regions)
    rule_id = _safe_rule_id(pid)

    return f"""\
# {pid}
# {rationale}
violation contains v if {{
    region := input.decorator.data["region"]
    not region in {regions_rego}
    v := {{
        "rule": "{rule_id}",
        "severity": "{severity}",
        "message": sprintf("Compliance boundary: region '%v' not in allowed set %v", [region, {regions_rego}]),
    }}
}}

"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_rule_id(policy_id: str) -> str:
    """Convert a Policy @id to a safe Rego string identifier."""
    return policy_id.replace("workload:", "").replace(":", ".").replace("/", "-")


def _context_label(predicate_type: str) -> str:
    if predicate_type in DRIFT_ENGINE:
        return "DRIFT_ENGINE"
    if predicate_type in RUNTIME:
        return "RUNTIME"
    return "UNKNOWN"
