# Generated by Weaver from semconv/forge. Do not edit by hand.
# Regenerate: scripts/generate-semconv.sh
#
# ADR-014 §1: emitters import these constants so an attribute that is not in the
# registry cannot be emitted. CI fails if this file is not current with the YAML.

from __future__ import annotations

# ---------------------------------------------------------------------------
# Resource attributes (ADR-009 §1)
# ---------------------------------------------------------------------------

FORGE_ANCHOR_REF = "forge.anchor.ref"

FORGE_PASSPORT_EDGE_DIGEST = "forge.passport.edge_digest"

FORGE_PASSPORT_EXPIRES = "forge.passport.expires"

FORGE_PASSPORT_ID = "forge.passport.id"

FORGE_WORKLOAD_URN = "forge.workload.urn"


# ---------------------------------------------------------------------------
# Log events (ADR-009 §2)
# ---------------------------------------------------------------------------

EVENT_FORGE_PASSPORT_ANNOUNCED = "forge.passport.announced"

EVENT_FORGE_PASSPORT_EXPIRING = "forge.passport.expiring"

EVENT_FORGE_PASSPORT_SUPERSEDED = "forge.passport.superseded"


RESOURCE_ATTRIBUTES: frozenset[str] = frozenset(
    {
        FORGE_ANCHOR_REF,
        FORGE_PASSPORT_EDGE_DIGEST,
        FORGE_PASSPORT_EXPIRES,
        FORGE_PASSPORT_ID,
        FORGE_WORKLOAD_URN,
    }
)

LOG_EVENTS: frozenset[str] = frozenset(
    {
        EVENT_FORGE_PASSPORT_ANNOUNCED,
        EVENT_FORGE_PASSPORT_EXPIRING,
        EVENT_FORGE_PASSPORT_SUPERSEDED,
    }
)