"""Sentinel policy generation — compliance gates from CALM metadata."""


def _header(metadata):
    compliance = metadata.get("compliance-scope", "general")
    data_class = metadata.get("data-classification", "internal")
    return (
        "# ============================================================\n"
        "# GENERATED BY: CALM Forge v0.2\n"
        f"# Compliance scope: {compliance} | Data classification: {data_class}\n"
        "# DO NOT EDIT — regenerate from CALM source\n"
        "# ============================================================\n"
    )


def write_sentinel_policies(metadata, component_map, decorators):
    """Generate sentinel/policies.sentinel — compliance policy set.

    - PCI-DSS scope → encryption-at-rest + no-public-endpoints policies
    - All scopes → cost threshold policy (advisory $500, soft $5k, hard $25k)
    - Confidential data → tagging requirements
    """
    compliance = metadata.get("compliance-scope", "general")
    data_class = metadata.get("data-classification", "internal")
    app_name = metadata.get("application-name", "app")

    lines = [_header(metadata)]
    lines.append('import "tfplan/v2" as tfplan')
    lines.append('import "tfrun"')
    lines.append("")

    # --- PCI-DSS: Encryption at rest ---
    if compliance == "pci-dss":
        lines.append("# ============================================================")
        lines.append("# Encryption at rest — PCI-DSS 3.4")
        lines.append("# All storage resources must enable server-side encryption.")
        lines.append("# ============================================================")
        lines.append("")
        lines.append("encryption_violations = filter tfplan.resource_changes as _, rc {")
        lines.append('  rc.type is "azurerm_storage_account" and')
        lines.append("  rc.change.after.enable_https_traffic_only is not true")
        lines.append("}")
        lines.append("")
        lines.append("storage_encryption_violations = filter tfplan.resource_changes as _, rc {")
        lines.append('  rc.type is "azurerm_managed_disk" and')
        lines.append('  (rc.change.after.encryption_settings is null or')
        lines.append('   rc.change.after.encryption_settings.enabled is not true)')
        lines.append("}")
        lines.append("")
        lines.append('rule "enforce_encryption_at_rest" {')
        lines.append("  condition = length(encryption_violations) is 0 and")
        lines.append("              length(storage_encryption_violations) is 0")
        lines.append('  enforcement_level = "hard-mandatory"')
        lines.append("}")
        lines.append("")

        # --- PCI-DSS: No public endpoints ---
        lines.append("# ============================================================")
        lines.append("# No public endpoints — PCI-DSS 1.3")
        lines.append("# PCI-scoped workloads must not expose public ingress.")
        lines.append("# ============================================================")
        lines.append("")
        lines.append("public_ingress_violations = filter tfplan.resource_changes as _, rc {")
        lines.append('  rc.type is "kubernetes_ingress_v1" and')
        lines.append('  rc.change.after.metadata[0].annotations["kubernetes.io/ingress.class"] is "public"')
        lines.append("}")
        lines.append("")
        lines.append("public_lb_violations = filter tfplan.resource_changes as _, rc {")
        lines.append('  rc.type is "kubernetes_service_v1" and')
        lines.append('  rc.change.after.spec[0].type is "LoadBalancer" and')
        lines.append('  (rc.change.after.metadata[0].annotations["service.beta.kubernetes.io/azure-load-balancer-internal"] is not "true")')
        lines.append("}")
        lines.append("")
        lines.append('rule "deny_public_endpoints" {')
        lines.append("  condition = length(public_ingress_violations) is 0 and")
        lines.append("              length(public_lb_violations) is 0")
        lines.append('  enforcement_level = "hard-mandatory"')
        lines.append("}")
        lines.append("")

    # --- Cost governance (all scopes) ---
    lines.append("# ============================================================")
    lines.append("# Cost governance — budget thresholds")
    lines.append(f"# Application: {app_name}")
    lines.append("# ============================================================")
    lines.append("")
    lines.append('rule "cost_advisory" {')
    lines.append("  condition = decimal(tfrun.cost_estimate.delta_monthly_cost) < 500")
    lines.append('  enforcement_level = "advisory"')
    lines.append("}")
    lines.append("")
    lines.append('rule "cost_soft_limit" {')
    lines.append("  condition = decimal(tfrun.cost_estimate.delta_monthly_cost) < 5000")
    lines.append('  enforcement_level = "soft-mandatory"')
    lines.append("}")
    lines.append("")
    lines.append('rule "cost_hard_limit" {')
    lines.append("  condition = decimal(tfrun.cost_estimate.delta_monthly_cost) < 25000")
    lines.append('  enforcement_level = "hard-mandatory"')
    lines.append("}")
    lines.append("")

    # --- Confidential data: tagging requirements ---
    if data_class == "confidential":
        lines.append("# ============================================================")
        lines.append("# Tagging requirements — confidential data classification")
        lines.append("# All resources must carry data-classification tag.")
        lines.append("# ============================================================")
        lines.append("")
        lines.append("tagging_violations = filter tfplan.resource_changes as _, rc {")
        lines.append('  rc.change.after.tags is not null and')
        lines.append('  rc.change.after.tags does not contain "data-classification"')
        lines.append("}")
        lines.append("")
        lines.append('rule "require_data_classification_tag" {')
        lines.append("  condition = length(tagging_violations) is 0")
        lines.append('  enforcement_level = "hard-mandatory"')
        lines.append("}")
        lines.append("")

    return "\n".join(lines)
