"""Terraform Policy (tfpolicy) generation — the third compilation target.

Companion to `sentinel_writer.py`. Both take the same CALM metadata and project it
into a policy framework; only the concrete syntax differs. Neither is authoritative —
each is an independent projection of the same CALM intent (ADR: tfpolicy compilation
target; ADR-004 §11 for the authority-class bridge).

**Parity is by construction.** `predicates_for(metadata)` names which predicates a given
CALM intent enforces. Both this emitter and the parity test derive from it, so the
Sentinel and tfpolicy emissions enforce the same predicate set for the same intent or
the parity test fails.

**[BETA]** tfpolicy is beta upstream at HashiCorp. Syntax may change between beta
releases; emitted artifacts and CLI help carry a [BETA] marker until HashiCorp GAs it.

**Resource-type note:** the ADR's §5 mapping table uses AWS resources as *syntax*
illustration. This emitter enforces the same predicates against the same resource types
the Sentinel emitter targets (azurerm / kubernetes), because parity is with the shipped
Sentinel policies, not with the illustration. When a customer's stack is AWS, the
resource types are a per-customer ratification step (ADR follow-up #1).
"""

from __future__ import annotations

from typing import Any

from .policy_targets import (
    AWS_ENCRYPTION_AT_REST,
    AWS_ENCRYPTION_TODO,
    AWS_NO_PUBLIC_ENDPOINTS,
    AWS_PUBLIC_ENDPOINT_TODO,
    cloud_provider_of,
)

# Canonical predicate keys. A CALM intent enforces some subset of these; the subset is a
# pure function of metadata (`predicates_for`). This is the finite, shared vocabulary that
# makes Sentinel/tfpolicy parity provable rather than aspirational.
PREDICATE_ENCRYPTION_AT_REST = "encryption_at_rest"
PREDICATE_NO_PUBLIC_ENDPOINTS = "no_public_endpoints"
PREDICATE_COST_GOVERNANCE = "cost_governance"
PREDICATE_DATA_CLASSIFICATION_TAG = "data_classification_tag"

# CALM authority class → tfpolicy enforcement_level. This is the APP bridge: the same
# safety split that gates the passport (claim.authority_class) gates the generated policy.
# Expansion is irreversible so it must block; contraction is reversible so a warning is
# acceptable. Note tfpolicy uses `mandatory`, not Sentinel's `hard-mandatory`.
_AUTHORITY_TO_LEVEL = {
    "governed-expansion": "mandatory",
    "autonomic-contraction": "advisory",
}
_DEFAULT_ENFORCEMENT_LEVEL = "soft-mandatory"


def enforcement_level_for_authority(authority_class: str | None) -> str:
    """Map a CALM authority class to a tfpolicy enforcement_level (APP bridge)."""
    return _AUTHORITY_TO_LEVEL.get(authority_class or "", _DEFAULT_ENFORCEMENT_LEVEL)


def predicates_for(metadata: dict[str, Any]) -> list[str]:
    """The ordered set of predicate keys a CALM intent enforces.

    Pure function of metadata. Both the Sentinel and tfpolicy emissions must reflect
    exactly this set for the same intent — that is the parity contract.
    """
    compliance = metadata.get("compliance-scope", "general")
    data_class = metadata.get("data-classification", "internal")

    predicates: list[str] = []
    if compliance == "pci-dss":
        predicates.append(PREDICATE_ENCRYPTION_AT_REST)
        predicates.append(PREDICATE_NO_PUBLIC_ENDPOINTS)
    # Cost governance applies to every scope, exactly as the Sentinel emitter does.
    predicates.append(PREDICATE_COST_GOVERNANCE)
    if data_class == "confidential":
        predicates.append(PREDICATE_DATA_CLASSIFICATION_TAG)
    return predicates


def _header(metadata: dict[str, Any]) -> str:
    compliance = metadata.get("compliance-scope", "general")
    data_class = metadata.get("data-classification", "internal")
    return (
        "# ============================================================\n"
        "# GENERATED BY: CALM Forge v0.2  [BETA: Terraform Policy]\n"
        f"# Compliance scope: {compliance} | Data classification: {data_class}\n"
        "# tfpolicy is beta upstream (HashiCorp). Syntax may change until GA.\n"
        "# DO NOT EDIT — regenerate from CALM source\n"
        "# ============================================================\n"
    )


def _policy_block(name: str, comment: str, level: str, resource_policies: list[str]) -> list[str]:
    """One named tfpolicy policy with its enforcement level and resource_policy blocks."""
    lines = [f"# {comment}", f'policy "{name}" {{', f'  enforcement_level = "{level}"', ""]
    lines.extend(resource_policies)
    lines.append("}")
    lines.append("")
    return lines


def _resource_policy(resource_type: str, condition: str) -> list[str]:
    return [
        f'  resource_policy "{resource_type}" {{',
        "    enforce {",
        f"      condition = {condition}",
        "    }",
        "  }",
        "",
    ]


def write_tfpolicy_policies(metadata: dict[str, Any], component_map=None, decorators=None) -> str:
    """Generate tfpolicy/policies.policy.hcl — same predicates as Sentinel, HCL syntax.

    Signature mirrors ``write_sentinel_policies`` so the generator wires it identically.
    """
    app_name = metadata.get("application-name", "app")
    predicates = predicates_for(metadata)
    cloud = cloud_provider_of(decorators)

    lines = [_header(metadata), ""]

    if PREDICATE_ENCRYPTION_AT_REST in predicates:
        if cloud == "aws":
            resource_policies: list[str] = []
            for t in AWS_ENCRYPTION_AT_REST:
                resource_policies += _resource_policy(t.resource_type, t.tfpolicy_condition)
            resource_policies.append(f"  # {AWS_ENCRYPTION_TODO}")
        else:
            resource_policies = (
                _resource_policy("azurerm_storage_account", "attrs.enable_https_traffic_only == true")
                + _resource_policy(
                    "azurerm_managed_disk",
                    "attrs.encryption_settings != null && attrs.encryption_settings.enabled == true",
                )
            )
        lines += _policy_block(
            "enforce_encryption_at_rest",
            "Encryption at rest — PCI-DSS 3.4",
            "mandatory",
            resource_policies,
        )

    if PREDICATE_NO_PUBLIC_ENDPOINTS in predicates:
        if cloud == "aws":
            resource_policies = []
            for t in AWS_NO_PUBLIC_ENDPOINTS:
                resource_policies += _resource_policy(t.resource_type, t.tfpolicy_condition)
            resource_policies.append(f"  # {AWS_PUBLIC_ENDPOINT_TODO}")
        else:
            resource_policies = (
                _resource_policy(
                    "kubernetes_ingress_v1",
                    'attrs.metadata.annotations["kubernetes.io/ingress.class"] != "public"',
                )
                + _resource_policy(
                    "kubernetes_service_v1",
                    'attrs.spec.type != "LoadBalancer" || '
                    'attrs.metadata.annotations["service.beta.kubernetes.io/azure-load-balancer-internal"] == "true"',
                )
            )
        lines += _policy_block(
            "deny_public_endpoints",
            "No public endpoints — PCI-DSS 1.3",
            "mandatory",
            resource_policies,
        )

    if PREDICATE_COST_GOVERNANCE in predicates:
        # 3-tier cost governance, mirroring the Sentinel advisory/soft/hard split.
        # tfpolicy has no `hard-mandatory`; the hard tier maps to `mandatory`.
        lines += _policy_block(
            "cost_advisory",
            f"Cost governance (advisory) — {app_name}",
            "advisory",
            ["  cost {", "    condition = plan.cost_estimate.delta_monthly_cost < 500", "  }", ""],
        )
        lines += _policy_block(
            "cost_soft_limit",
            "Cost governance (soft limit)",
            "soft-mandatory",
            ["  cost {", "    condition = plan.cost_estimate.delta_monthly_cost < 5000", "  }", ""],
        )
        lines += _policy_block(
            "cost_hard_limit",
            "Cost governance (hard limit)",
            "mandatory",
            ["  cost {", "    condition = plan.cost_estimate.delta_monthly_cost < 25000", "  }", ""],
        )

    if PREDICATE_DATA_CLASSIFICATION_TAG in predicates:
        lines += _policy_block(
            "require_data_classification_tag",
            "Tagging requirements — confidential data classification",
            "mandatory",
            _resource_policy("*", 'attrs.tags != null && contains(keys(attrs.tags), "data-classification")'),
        )

    return "\n".join(lines)


def write_tfpolicy_tests(metadata: dict[str, Any], component_map=None, decorators=None) -> str:
    """Generate tfpolicy/policies.policytest.hcl — mock resources per emitted policy.

    tfpolicy's native test format. Because both the policy and its test come from the
    same CALM intent, they agree by construction: a test exists for exactly the policies
    that were emitted.
    """
    predicates = predicates_for(metadata)
    cloud = cloud_provider_of(decorators)

    # The mock resource each test fixtures against must be a resource the emitted policy
    # actually checks — otherwise the test passes vacuously (mocks a type the policy never
    # inspects). So the mock type is provider-keyed, same as the policy body.
    if cloud == "aws":
        encryption_mock = AWS_ENCRYPTION_AT_REST[0].resource_type
        public_mock = AWS_NO_PUBLIC_ENDPOINTS[1].resource_type
        tag_mock = AWS_ENCRYPTION_AT_REST[0].resource_type
    else:
        encryption_mock = "azurerm_storage_account"
        public_mock = "kubernetes_ingress_v1"
        tag_mock = "azurerm_storage_account"

    lines = [
        "# ============================================================",
        "# GENERATED BY: CALM Forge v0.2  [BETA: Terraform Policy tests]",
        "# One test per emitted policy. Run with: tfpolicy test",
        "# DO NOT EDIT — regenerate from CALM source",
        "# ============================================================",
        "",
    ]

    def _test(policy_name: str, mock: str) -> list[str]:
        return [
            f'test "{policy_name}_passes" {{',
            f'  mock "{mock}" {{',
            "    # compliant fixture — the policy must PASS against this",
            "  }",
            f"  expect_pass = policy.{policy_name}",
            "}",
            "",
        ]

    if PREDICATE_ENCRYPTION_AT_REST in predicates:
        lines += _test("enforce_encryption_at_rest", encryption_mock)
    if PREDICATE_NO_PUBLIC_ENDPOINTS in predicates:
        lines += _test("deny_public_endpoints", public_mock)
    if PREDICATE_COST_GOVERNANCE in predicates:
        lines += _test("cost_advisory", "plan.cost_estimate")
    if PREDICATE_DATA_CLASSIFICATION_TAG in predicates:
        lines += _test("require_data_classification_tag", tag_mock)

    return "\n".join(lines)
