"""Vault HCL generation — policies, PKI config, and database engine from CALM."""


def _header():
    return (
        "# ============================================================\n"
        "# GENERATED BY: CALM Forge v0.2\n"
        "# DO NOT EDIT — regenerate from CALM source\n"
        "# ============================================================\n"
    )


def write_vault_policies(component_map, rel_components, metadata):
    """Generate vault/policies.hcl — least-privilege Vault policies per component.

    - service nodes → read DB creds, issue PKI certs, read KV config, Transit encrypt/decrypt
    - database nodes → auditor policy scoped to that engine
    """
    app_name = metadata.get("application-name", "app")
    compliance = metadata.get("compliance-scope", "general")

    # Determine which nodes participate in mTLS and DB relationships
    mtls_nodes = set()
    db_consumer_nodes = set()
    for rc in rel_components:
        rel = rc["relationship"]
        auth = rel.get("authentication", "")
        connects = rel["relationship-type"]["connects"]
        src = connects.get("source", {}).get("node")
        dst = connects.get("destination", {}).get("node")
        if auth == "mTLS-vault-pki":
            if src:
                mtls_nodes.add(src)
            if dst:
                mtls_nodes.add(dst)
        elif auth == "vault-dynamic-credentials":
            if src:
                db_consumer_nodes.add(src)

    lines = [_header()]
    lines.append(f"# Vault policies for {app_name} components")
    lines.append(f"# Compliance scope: {compliance}")
    lines.append("")

    for node_id, entry in component_map.items():
        node = entry["node"]
        node_type = node["node-type"]

        if node_type == "system":
            continue

        lines.append(f"# --- Policy: {node_id} ---")
        lines.append(f'path "kv/data/{app_name}/{node_id}/*" {{')
        lines.append('  capabilities = ["read", "list"]')
        lines.append("}")
        lines.append("")

        if node_type == "service":
            if node_id in mtls_nodes:
                lines.append(f'path "pki/{app_name}/issue/{node_id}" {{')
                lines.append('  capabilities = ["create", "update"]')
                lines.append("}")
                lines.append("")

            if node_id in db_consumer_nodes:
                lines.append(f'path "database/creds/{node_id}" {{')
                lines.append('  capabilities = ["read"]')
                lines.append("}")
                lines.append("")

            lines.append(f'path "transit/encrypt/{app_name}" {{')
            lines.append('  capabilities = ["update"]')
            lines.append("}")
            lines.append(f'path "transit/decrypt/{app_name}" {{')
            lines.append('  capabilities = ["update"]')
            lines.append("}")
            lines.append("")

        elif node_type == "database":
            lines.append(f'path "database/config/{app_name}-{node_id}" {{')
            lines.append('  capabilities = ["read"]')
            lines.append("}")
            lines.append(f'path "sys/mounts/database/{app_name}" {{')
            lines.append('  capabilities = ["read"]')
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def write_pki_config(component_map, rel_components, metadata, decorators):
    """Generate vault/pki-config.hcl — PKI mounts + DB engine as Terraform resources.

    For each mTLS relationship: PKI mount, intermediate CA, service role.
    For each vault-dynamic-credentials relationship: DB mount, connection, dynamic role.
    """
    app_name = metadata.get("application-name", "app")
    decorator = decorators[0] if decorators else {}
    dec_data = decorator.get("data", {})
    k8s = dec_data.get("kubernetes", {})
    namespace = k8s.get("namespace", app_name)

    lines = [_header()]
    lines.append(f"# Vault PKI and database engine configuration for {app_name}")
    lines.append("")

    for rc in rel_components:
        rel = rc["relationship"]
        auth = rel.get("authentication", "")
        connects = rel["relationship-type"]["connects"]
        src = connects.get("source", {}).get("node", "")
        dst = connects.get("destination", {}).get("node", "")

        if auth == "mTLS-vault-pki":
            lines.append(f"# --- PKI: {rel['unique-id']} ({src} → {dst}) ---")
            lines.append("")

            # PKI mount
            lines.append(f'resource "vault_mount" "pki_{app_name.replace("-", "_")}" {{')
            lines.append(f'  path                      = "pki/{app_name}"')
            lines.append('  type                      = "pki"')
            lines.append('  default_lease_ttl_seconds = 86400')
            lines.append('  max_lease_ttl_seconds     = 259200')
            lines.append("}")
            lines.append("")

            # Intermediate CA
            lines.append(
                f'resource "vault_pki_secret_backend_intermediate_cert_request" '
                f'"pki_{app_name.replace("-", "_")}_intermediate" {{'
            )
            lines.append(f'  backend     = vault_mount.pki_{app_name.replace("-", "_")}.path')
            lines.append('  type        = "internal"')
            lines.append(f'  common_name = "{app_name} Intermediate CA"')
            lines.append('  key_type    = "ec"')
            lines.append('  key_bits    = 256')
            lines.append("}")
            lines.append("")

            # Service roles for source and destination
            for node_id in [src, dst]:
                if not node_id:
                    continue
                hcl_id = node_id.replace("-", "_")
                lines.append(f'resource "vault_pki_secret_backend_role" "{hcl_id}" {{')
                lines.append(f'  backend          = vault_mount.pki_{app_name.replace("-", "_")}.path')
                lines.append(f'  name             = "{node_id}"')
                lines.append(f'  allowed_domains  = ["{node_id}.{namespace}.svc"]')
                lines.append('  allow_subdomains = false')
                lines.append('  allow_bare_domains = true')
                lines.append('  allow_glob_domains = false')
                lines.append('  allow_wildcard_certificates = false')
                lines.append('  enforce_hostnames = true')
                lines.append('  key_type         = "ec"')
                lines.append('  key_bits         = 256')
                lines.append('  max_ttl          = "72h"')
                lines.append('  ttl              = "24h"')
                lines.append("}")
                lines.append("")

        elif auth == "vault-dynamic-credentials":
            lines.append(f"# --- Database engine: {rel['unique-id']} ({src} → {dst}) ---")
            lines.append("")

            # DB mount
            lines.append(f'resource "vault_mount" "db_{app_name.replace("-", "_")}" {{')
            lines.append(f'  path = "database/{app_name}"')
            lines.append('  type = "database"')
            lines.append("}")
            lines.append("")

            # PostgreSQL connection
            dst_hcl = dst.replace("-", "_") if dst else "database"
            lines.append(
                f'resource "vault_database_secret_backend_connection" '
                f'"{dst_hcl}" {{'
            )
            lines.append(f'  backend       = vault_mount.db_{app_name.replace("-", "_")}.path')
            lines.append(f'  name           = "{dst}"')
            lines.append(f'  allowed_roles  = ["{src}"]')
            lines.append("")
            lines.append("  postgresql {")
            lines.append(
                f'    connection_url = "postgresql://{{{{username}}}}:{{{{password}}}}@'
                f'{dst}.{namespace}.svc:5432/{app_name}?sslmode=verify-full"'
            )
            lines.append("  }")
            lines.append("}")
            lines.append("")

            # Dynamic role
            src_hcl = src.replace("-", "_") if src else "app"
            lines.append(f'resource "vault_database_secret_backend_role" "{src_hcl}" {{')
            lines.append(f'  backend             = vault_mount.db_{app_name.replace("-", "_")}.path')
            lines.append(f'  name                = "{src}"')
            lines.append(f'  db_name             = vault_database_secret_backend_connection.{dst_hcl}.name')
            lines.append('  default_ttl         = 1800')
            lines.append('  max_ttl             = 7200')
            lines.append('  creation_statements = [')
            lines.append(f'    "CREATE ROLE \\"{{{{name}}}}\\" WITH LOGIN PASSWORD \'{{{{password}}}}\' '
                         f'VALID UNTIL \'{{{{expiration}}}}\' IN ROLE \\"{src}\\";"')
            lines.append("  ]")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)
