# ============================================================
# GENERATED BY: CALM Forge v0.1
# SOURCE:       fraud-detection-pipeline.architecture.json
# PATTERN:      fraud-detection-pipeline.pattern.json
# DO NOT EDIT — regenerate from CALM source
# ============================================================

required_providers {
  kubernetes = {
    source  = "hashicorp/kubernetes"
    version = "~> 2.30"
  }
  vault = {
    source  = "hashicorp/vault"
    version = "~> 4.2"
  }
  helm = {
    source  = "hashicorp/helm"
    version = "~> 2.13"
  }
}

provider "kubernetes" "ocp" {
  config_path = var.kubeconfig_path
}

provider "vault" "this" {
  address = var.vault_addr
  token   = var.vault_token
}

provider "helm" "this" {
  kubernetes {
    config_path = var.kubeconfig_path
  }
}

# --- Component: transaction-ingest ---
# CALM node: transaction-ingest (service)
# Module: registry.terraform.io/financial-crimes/network-offload-service/v1.0.0
component "transaction_ingest" {
  source = "registry.terraform.io/financial-crimes/network-offload-service/v1.0.0"

  inputs = {
    name             = "transaction-ingest"
    namespace        = var.namespace
    container_image  = "registry.internal/fraud/ingest:3.2.1"
    replicas         = 4
    cpu_request      = "2000m"
    memory_request   = "4Gi"
    port             = 8443
    protocol         = "HTTPS"
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: ml-scoring ---
# CALM node: ml-scoring (service)
# Module: registry.terraform.io/financial-crimes/confidential-compute-workload/v1.0.0
component "ml_scoring" {
  source = "registry.terraform.io/financial-crimes/confidential-compute-workload/v1.0.0"

  inputs = {
    name             = "ml-scoring"
    namespace        = var.namespace
    container_image  = "registry.internal/fraud/scoring:1.8.0"
    replicas         = 6
    cpu_request      = "4000m"
    memory_request   = "16Gi"
    port             = 8443
    protocol         = "HTTPS"
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: external-state ---
# CALM node: external-state (service)
# Module: registry.terraform.io/financial-crimes/portable-state-layer/v1.0.0
component "external_state" {
  source = "registry.terraform.io/financial-crimes/portable-state-layer/v1.0.0"

  inputs = {
    name             = "external-state"
    namespace        = var.namespace
    container_image  = "registry.internal/fraud/state:2.0.0"
    replicas         = 3
    cpu_request      = "1000m"
    memory_request   = "32Gi"
    port             = 8443
    protocol         = "HTTPS"
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: decision-emitter ---
# CALM node: decision-emitter (service)
# Module: registry.terraform.io/financial-crimes/ocp-service/v2.0.0
component "decision_emitter" {
  source = "registry.terraform.io/financial-crimes/ocp-service/v2.0.0"

  inputs = {
    name             = "decision-emitter"
    namespace        = var.namespace
    container_image  = "registry.internal/fraud/decision:1.4.0"
    replicas         = 2
    cpu_request      = "500m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "decision-emitter"
    service_mesh     = true
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: decision-to-gateway (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/financial-crimes/vault-pki-mtls/v2.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/financial-crimes/vault-pki-mtls/v2.0.0"

  inputs = {
    pki_mount_path    = "pki/fraud-detection-pipeline"
    allowed_domains   = ["decision-emitter.${var.namespace}.svc", "payment-gateway.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}
