# ============================================================
# GENERATED BY: CALM Forge v0.1
# SOURCE:       fraud-detection-pipeline-prod-capability-001 (deployment decorator)
# PLACEMENT:    Placement Engine decision — see rationale ref
# ============================================================

identity_token "vault" {
  audience = ["vault.uhccp.internal"]
}

# --- Deployment: production (from CALM deployment decorator) ---
# Cluster: capability-resolved
# Region:  default (Unknown)
# Reason:  PCI-DSS requires UK data residency, cluster has 40% headroom,
#          cost within budget envelope CC-8800
deployment "production" {
  inputs = {
    namespace         = "fraud-detection"
    kubeconfig_path   = "/etc/kubernetes/capability-resolved.kubeconfig"
    vault_addr        = "https://vault.production.default.uhccp.internal:8200"
    vault_token       = identity_token.vault.jwt
    vault_transit_key = "fraud-detection-pipeline-transit"
    environment       = "production"
  }
}

# --- Deployment group: production gate ---
deployment_auto_approve "no_destroys" {
  check {
    condition = context.plan.changes.remove == 0
    reason    = "Plan would destroy ${context.plan.changes.remove} resources. Manual approval required."
  }
}

deployment_auto_approve "no_pci_scope_change" {
  check {
    condition = context.plan.applyable == true
    reason    = "PCI-scoped deployment requires manual approval for any infrastructure change."
  }
}

deployment_group "production_gate" {
  auto_approve_checks = [
    deployment_auto_approve.no_destroys
  ]
  # Note: PCI-scoped deployments always require manual approval
  # deployment_auto_approve.no_pci_scope_change is informational
}

# --- Staging deployment (auto-generated for pre-prod validation) ---
deployment "staging" {
  inputs = {
    namespace         = "fraud-detection-pipeline-staging"
    kubeconfig_path   = "/etc/kubernetes/staging-default-ocp-01.kubeconfig"
    vault_addr        = "https://vault.staging.default.uhccp.internal:8200"
    vault_token       = identity_token.vault.jwt
    vault_transit_key = "fraud-detection-pipeline-transit-staging"
    environment       = "staging"
  }
}
