# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault PKI and database engine configuration for portfolio-platform

# --- PKI: glb-to-api-useast (global-load-balancer → portfolio-api-useast) ---

resource "vault_mount" "pki_portfolio_platform" {
  path                      = "pki/portfolio-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_portfolio_platform_intermediate" {
  backend     = vault_mount.pki_portfolio_platform.path
  type        = "internal"
  common_name = "portfolio-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "global_load_balancer" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "global-load-balancer"
  allowed_domains  = ["global-load-balancer.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "portfolio_api_useast" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "portfolio-api-useast"
  allowed_domains  = ["portfolio-api-useast.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- PKI: glb-to-api-uswest (global-load-balancer → portfolio-api-uswest) ---

resource "vault_mount" "pki_portfolio_platform" {
  path                      = "pki/portfolio-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_portfolio_platform_intermediate" {
  backend     = vault_mount.pki_portfolio_platform.path
  type        = "internal"
  common_name = "portfolio-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "global_load_balancer" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "global-load-balancer"
  allowed_domains  = ["global-load-balancer.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "portfolio_api_uswest" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "portfolio-api-uswest"
  allowed_domains  = ["portfolio-api-uswest.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- PKI: glb-to-api-euwest (global-load-balancer → portfolio-api-euwest) ---

resource "vault_mount" "pki_portfolio_platform" {
  path                      = "pki/portfolio-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_portfolio_platform_intermediate" {
  backend     = vault_mount.pki_portfolio_platform.path
  type        = "internal"
  common_name = "portfolio-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "global_load_balancer" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "global-load-balancer"
  allowed_domains  = ["global-load-balancer.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "portfolio_api_euwest" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "portfolio-api-euwest"
  allowed_domains  = ["portfolio-api-euwest.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- PKI: replication-primary-to-uswest (mongodb-primary → mongodb-secondary-uswest) ---

resource "vault_mount" "pki_portfolio_platform" {
  path                      = "pki/portfolio-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_portfolio_platform_intermediate" {
  backend     = vault_mount.pki_portfolio_platform.path
  type        = "internal"
  common_name = "portfolio-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "mongodb_primary" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "mongodb-primary"
  allowed_domains  = ["mongodb-primary.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "mongodb_secondary_uswest" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "mongodb-secondary-uswest"
  allowed_domains  = ["mongodb-secondary-uswest.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- PKI: replication-primary-to-euwest (mongodb-primary → mongodb-secondary-euwest) ---

resource "vault_mount" "pki_portfolio_platform" {
  path                      = "pki/portfolio-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_portfolio_platform_intermediate" {
  backend     = vault_mount.pki_portfolio_platform.path
  type        = "internal"
  common_name = "portfolio-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "mongodb_primary" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "mongodb-primary"
  allowed_domains  = ["mongodb-primary.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "mongodb_secondary_euwest" {
  backend          = vault_mount.pki_portfolio_platform.path
  name             = "mongodb-secondary-euwest"
  allowed_domains  = ["mongodb-secondary-euwest.portfolio-platform.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}
