# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault policies for portfolio-platform components
# Compliance scope: ['sox', 'pci-dss']

# --- Policy: portfolio-api-useast ---
path "kv/data/portfolio-platform/portfolio-api-useast/*" {
  capabilities = ["read", "list"]
}

path "pki/portfolio-platform/issue/portfolio-api-useast" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/portfolio-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/portfolio-platform" {
  capabilities = ["update"]
}

# --- Policy: portfolio-api-uswest ---
path "kv/data/portfolio-platform/portfolio-api-uswest/*" {
  capabilities = ["read", "list"]
}

path "pki/portfolio-platform/issue/portfolio-api-uswest" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/portfolio-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/portfolio-platform" {
  capabilities = ["update"]
}

# --- Policy: portfolio-api-euwest ---
path "kv/data/portfolio-platform/portfolio-api-euwest/*" {
  capabilities = ["read", "list"]
}

path "pki/portfolio-platform/issue/portfolio-api-euwest" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/portfolio-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/portfolio-platform" {
  capabilities = ["update"]
}

# --- Policy: mongodb-primary ---
path "kv/data/portfolio-platform/mongodb-primary/*" {
  capabilities = ["read", "list"]
}

path "database/config/portfolio-platform-mongodb-primary" {
  capabilities = ["read"]
}
path "sys/mounts/database/portfolio-platform" {
  capabilities = ["read"]
}

# --- Policy: mongodb-secondary-uswest ---
path "kv/data/portfolio-platform/mongodb-secondary-uswest/*" {
  capabilities = ["read", "list"]
}

path "database/config/portfolio-platform-mongodb-secondary-uswest" {
  capabilities = ["read"]
}
path "sys/mounts/database/portfolio-platform" {
  capabilities = ["read"]
}

# --- Policy: mongodb-secondary-euwest ---
path "kv/data/portfolio-platform/mongodb-secondary-euwest/*" {
  capabilities = ["read", "list"]
}

path "database/config/portfolio-platform-mongodb-secondary-euwest" {
  capabilities = ["read"]
}
path "sys/mounts/database/portfolio-platform" {
  capabilities = ["read"]
}

# --- Policy: global-load-balancer ---
path "kv/data/portfolio-platform/global-load-balancer/*" {
  capabilities = ["read", "list"]
}

path "pki/portfolio-platform/issue/global-load-balancer" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/portfolio-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/portfolio-platform" {
  capabilities = ["update"]
}
