# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault PKI and database engine configuration for trade-pipeline

# --- Database engine: trade-processor-to-db (trade-processor → postgres-db) ---

resource "vault_mount" "db_trade_pipeline" {
  path = "database/trade-pipeline"
  type = "database"
}

resource "vault_database_secret_backend_connection" "postgres_db" {
  backend       = vault_mount.db_trade_pipeline.path
  name           = "postgres-db"
  allowed_roles  = ["trade-processor"]

  postgresql {
    connection_url = "postgresql://{{username}}:{{password}}@postgres-db.trade-pipeline-prod.svc:5432/trade-pipeline?sslmode=verify-full"
  }
}

resource "vault_database_secret_backend_role" "trade_processor" {
  backend             = vault_mount.db_trade_pipeline.path
  name                = "trade-processor"
  db_name             = vault_database_secret_backend_connection.postgres_db.name
  default_ttl         = 1800
  max_ttl             = 7200
  creation_statements = [
    "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}' IN ROLE \"trade-processor\";"
  ]
}

# --- Database engine: settlement-engine-to-db (settlement-engine → postgres-db) ---

resource "vault_mount" "db_trade_pipeline" {
  path = "database/trade-pipeline"
  type = "database"
}

resource "vault_database_secret_backend_connection" "postgres_db" {
  backend       = vault_mount.db_trade_pipeline.path
  name           = "postgres-db"
  allowed_roles  = ["settlement-engine"]

  postgresql {
    connection_url = "postgresql://{{username}}:{{password}}@postgres-db.trade-pipeline-prod.svc:5432/trade-pipeline?sslmode=verify-full"
  }
}

resource "vault_database_secret_backend_role" "settlement_engine" {
  backend             = vault_mount.db_trade_pipeline.path
  name                = "settlement-engine"
  db_name             = vault_database_secret_backend_connection.postgres_db.name
  default_ttl         = 1800
  max_ttl             = 7200
  creation_statements = [
    "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}' IN ROLE \"settlement-engine\";"
  ]
}
