# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault policies for trade-pipeline components
# Compliance scope: pci-dss

# --- Policy: order-intake ---
path "kv/data/trade-pipeline/order-intake/*" {
  capabilities = ["read", "list"]
}

path "transit/encrypt/trade-pipeline" {
  capabilities = ["update"]
}
path "transit/decrypt/trade-pipeline" {
  capabilities = ["update"]
}

# --- Policy: kafka-cluster ---
path "kv/data/trade-pipeline/kafka-cluster/*" {
  capabilities = ["read", "list"]
}

# --- Policy: trade-processor ---
path "kv/data/trade-pipeline/trade-processor/*" {
  capabilities = ["read", "list"]
}

path "database/creds/trade-processor" {
  capabilities = ["read"]
}

path "transit/encrypt/trade-pipeline" {
  capabilities = ["update"]
}
path "transit/decrypt/trade-pipeline" {
  capabilities = ["update"]
}

# --- Policy: settlement-engine ---
path "kv/data/trade-pipeline/settlement-engine/*" {
  capabilities = ["read", "list"]
}

path "database/creds/settlement-engine" {
  capabilities = ["read"]
}

path "transit/encrypt/trade-pipeline" {
  capabilities = ["update"]
}
path "transit/decrypt/trade-pipeline" {
  capabilities = ["update"]
}

# --- Policy: audit-logger ---
path "kv/data/trade-pipeline/audit-logger/*" {
  capabilities = ["read", "list"]
}

path "transit/encrypt/trade-pipeline" {
  capabilities = ["update"]
}
path "transit/decrypt/trade-pipeline" {
  capabilities = ["update"]
}

# --- Policy: postgres-db ---
path "kv/data/trade-pipeline/postgres-db/*" {
  capabilities = ["read", "list"]
}

path "database/config/trade-pipeline-postgres-db" {
  capabilities = ["read"]
}
path "sys/mounts/database/trade-pipeline" {
  capabilities = ["read"]
}
