# ============================================================
# GENERATED BY: CALM Forge v0.1
# SOURCE:       portfolio-platform.architecture.json
# PATTERN:      fsi-mongodb-multiregion.pattern.json
# GENERATED:    (timestamp varies)
# DO NOT EDIT — regenerate from CALM source
# ============================================================

required_providers {
  kubernetes = {
    source  = "hashicorp/kubernetes"
    version = "~> 2.30"
  }
  vault = {
    source  = "hashicorp/vault"
    version = "~> 4.2"
  }
  helm = {
    source  = "hashicorp/helm"
    version = "~> 2.13"
  }
}

provider "kubernetes" "ocp" {
  config_path = var.kubeconfig_path
}

provider "vault" "this" {
  address = var.vault_addr
  token   = var.vault_token
}

provider "helm" "this" {
  kubernetes {
    config_path = var.kubeconfig_path
  }
}

# --- Component: portfolio-api-useast ---
# CALM node: portfolio-api-useast (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "portfolio_api_useast" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "portfolio-api-useast"
    namespace        = var.namespace
    container_image  = "registry.internal/portfolio/api:2.8.0"
    replicas         = 3
    cpu_request      = "1000m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "portfolio-api-useast"
    service_mesh     = true
    db_connection    = component.mongodb_primary.outputs.connection_string
    db_vault_path    = component.vault_dynamic_db_creds.outputs.creds_path
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: portfolio-api-uswest ---
# CALM node: portfolio-api-uswest (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "portfolio_api_uswest" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "portfolio-api-uswest"
    namespace        = var.namespace
    container_image  = "registry.internal/portfolio/api:2.8.0"
    replicas         = 3
    cpu_request      = "1000m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "portfolio-api-uswest"
    service_mesh     = true
    db_connection    = component.mongodb_secondary_uswest.outputs.connection_string
    db_vault_path    = component.vault_dynamic_db_creds.outputs.creds_path
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: portfolio-api-euwest ---
# CALM node: portfolio-api-euwest (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "portfolio_api_euwest" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "portfolio-api-euwest"
    namespace        = var.namespace
    container_image  = "registry.internal/portfolio/api:2.8.0"
    replicas         = 3
    cpu_request      = "1000m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "portfolio-api-euwest"
    service_mesh     = true
    db_connection    = component.mongodb_secondary_euwest.outputs.connection_string
    db_vault_path    = component.vault_dynamic_db_creds.outputs.creds_path
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: mongodb-primary ---
# CALM node: mongodb-primary (database, engine=mongodb)
# Module: registry.terraform.io/uhccp/mongodb-ocp-primary/v1.0.0
component "mongodb_primary" {
  source = "registry.terraform.io/uhccp/mongodb-ocp-primary/v1.0.0"

  inputs = {
    name           = "portfolio-platform-db"
    namespace      = var.namespace
    version        = "7.0"
    storage_class  = "encrypted-ssd"
    storage_size   = "500Gi"
    vault_addr     = var.vault_addr
    encryption_key = var.vault_transit_key
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
    helm       = provider.helm.this
  }
}

# --- Component: mongodb-secondary-uswest ---
# CALM node: mongodb-secondary-uswest (database, engine=mongodb)
# Module: registry.terraform.io/uhccp/mongodb-ocp-secondary/v1.0.0
component "mongodb_secondary_uswest" {
  source = "registry.terraform.io/uhccp/mongodb-ocp-secondary/v1.0.0"

  inputs = {
    name           = "portfolio-platform-db"
    namespace      = var.namespace
    version        = "7.0"
    storage_class  = "encrypted-ssd"
    storage_size   = "500Gi"
    vault_addr     = var.vault_addr
    encryption_key = var.vault_transit_key
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
    helm       = provider.helm.this
  }
}

# --- Component: mongodb-secondary-euwest ---
# CALM node: mongodb-secondary-euwest (database, engine=mongodb)
# Module: registry.terraform.io/uhccp/mongodb-ocp-secondary/v1.0.0
component "mongodb_secondary_euwest" {
  source = "registry.terraform.io/uhccp/mongodb-ocp-secondary/v1.0.0"

  inputs = {
    name           = "portfolio-platform-db"
    namespace      = var.namespace
    version        = "7.0"
    storage_class  = "encrypted-ssd"
    storage_size   = "500Gi"
    vault_addr     = var.vault_addr
    encryption_key = var.vault_transit_key
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
    helm       = provider.helm.this
  }
}

# --- Component: global-load-balancer ---
# CALM node: global-load-balancer (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "global_load_balancer" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "global-load-balancer"
    namespace        = var.namespace
    container_image  = ""
    replicas         = 1
    cpu_request      = "500m"
    memory_request   = "512Mi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "global-load-balancer"
    service_mesh     = true
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: glb-to-api-useast (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/portfolio-platform"
    allowed_domains   = ["global-load-balancer.${var.namespace}.svc", "portfolio-api-useast.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: glb-to-api-uswest (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/portfolio-platform"
    allowed_domains   = ["global-load-balancer.${var.namespace}.svc", "portfolio-api-uswest.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: glb-to-api-euwest (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/portfolio-platform"
    allowed_domains   = ["global-load-balancer.${var.namespace}.svc", "portfolio-api-euwest.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: replication-primary-to-uswest (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/portfolio-platform"
    allowed_domains   = ["mongodb-primary.${var.namespace}.svc", "mongodb-secondary-uswest.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: replication-primary-to-euwest (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/portfolio-platform"
    allowed_domains   = ["mongodb-primary.${var.namespace}.svc", "mongodb-secondary-euwest.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}
