# ============================================================
# GENERATED BY: CALM Forge v0.1
# SOURCE:       portfolio-platform-prod-multiregion-001 (deployment decorator)
# PLACEMENT:    Placement Engine decision — see rationale ref
# ============================================================

identity_token "vault" {
  audience = ["vault.uhccp.internal"]
}

# --- Deployment: production (from CALM deployment decorator) ---
# Cluster: default
# Region:  default (Unknown)
deployment "production" {
  inputs = {
    namespace         = "production"
    kubeconfig_path   = "/etc/kubernetes/default.kubeconfig"
    vault_addr        = "https://vault.production.default.uhccp.internal:8200"
    vault_token       = identity_token.vault.jwt
    vault_transit_key = "portfolio-platform-transit"
    environment       = "production"
  }
}

# --- Staging deployment (auto-generated for pre-prod validation) ---
deployment "staging" {
  inputs = {
    namespace         = "portfolio-platform-staging"
    kubeconfig_path   = "/etc/kubernetes/staging-default-ocp-01.kubeconfig"
    vault_addr        = "https://vault.staging.default.uhccp.internal:8200"
    vault_token       = identity_token.vault.jwt
    vault_transit_key = "portfolio-platform-transit-staging"
    environment       = "staging"
  }
}
