# ============================================================
# GENERATED BY: CALM Forge v0.1
# SOURCE:       payments-portal.architecture.json
# PATTERN:      fsi-3tier-app.pattern.json
# DO NOT EDIT — regenerate from CALM source
# ============================================================

required_providers {
  kubernetes = {
    source  = "hashicorp/kubernetes"
    version = "~> 2.30"
  }
  vault = {
    source  = "hashicorp/vault"
    version = "~> 4.2"
  }
  helm = {
    source  = "hashicorp/helm"
    version = "~> 2.13"
  }
}

provider "kubernetes" "ocp" {
  config_path = var.kubeconfig_path
}

provider "vault" "this" {
  address = var.vault_addr
  token   = var.vault_token
}

provider "helm" "this" {
  kubernetes {
    config_path = var.kubeconfig_path
  }
}

# --- Component: web-frontend ---
# CALM node: web-frontend (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "web_frontend" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "web-frontend"
    namespace        = var.namespace
    container_image  = "registry.internal/payments/web:3.2.1"
    replicas         = 3
    cpu_request      = "500m"
    memory_request   = "512Mi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "web-frontend"
    service_mesh     = true
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: api-service ---
# CALM node: api-service (service)
# Module: registry.terraform.io/uhccp/ocp-deployment/v2.1.0
component "api_service" {
  source = "registry.terraform.io/uhccp/ocp-deployment/v2.1.0"

  inputs = {
    name             = "api-service"
    namespace        = var.namespace
    container_image  = "registry.internal/payments/api:3.2.1"
    replicas         = 3
    cpu_request      = "1000m"
    memory_request   = "1Gi"
    port             = 8443
    protocol         = "HTTPS"
    vault_pki_path   = component.vault_pki_mtls.outputs.pki_path
    vault_role       = "api-service"
    service_mesh     = true
    db_connection    = component.database.outputs.connection_string
    db_vault_path    = component.vault_dynamic_db_creds.outputs.creds_path
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
  }
}

# --- Component: database ---
# CALM node: database (database, engine=postgresql)
# Module: registry.terraform.io/uhccp/crunchydata-postgres/v1.3.0
component "database" {
  source = "registry.terraform.io/uhccp/crunchydata-postgres/v1.3.0"

  inputs = {
    name           = "payments-portal-db"
    namespace      = var.namespace
    version        = "15.4"
    storage_class  = "encrypted-ssd"
    storage_size   = "100Gi"
    vault_addr     = var.vault_addr
    encryption_key = var.vault_transit_key
  }

  providers = {
    kubernetes = provider.kubernetes.ocp
    vault      = provider.vault.this
    helm       = provider.helm.this
  }
}

# --- Component: vault-pki-mtls ---
# CALM relationship: web-to-api (authentication=mTLS-vault-pki)
# Module: registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0
component "vault_pki_mtls" {
  source = "registry.terraform.io/uhccp/vault-pki-mtls/v1.0.0"

  inputs = {
    pki_mount_path    = "pki/payments-portal"
    allowed_domains   = ["web-frontend.${var.namespace}.svc", "api-service.${var.namespace}.svc"]
    max_ttl           = "24h"
    default_ttl       = "1h"
  }

  providers = {
    vault = provider.vault.this
  }
}

# --- Component: vault-dynamic-db-creds ---
# CALM relationship: api-to-db (authentication=vault-dynamic-credentials)
# Module: registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0
component "vault_dynamic_db_creds" {
  source = "registry.terraform.io/uhccp/vault-dynamic-db-creds/v1.0.0"

  inputs = {
    db_mount_path     = "database/payments-portal"
    db_connection_url = component.database.outputs.connection_string
    allowed_roles     = ["api-service"]
    default_ttl       = "1h"
    max_ttl           = "24h"
  }

  providers = {
    vault = provider.vault.this
  }
}
