# ============================================================
# GENERATED BY: CALM Forge v0.1
# ============================================================

variable "namespace" {
  type        = string
  description = "Kubernetes namespace for deployment"
}

variable "kubeconfig_path" {
  type        = string
  description = "Path to kubeconfig for target OCP cluster"
}

variable "vault_addr" {
  type        = string
  description = "Vault server address"
}

variable "vault_token" {
  type        = string
  description = "Vault authentication token"
  sensitive   = true
}

variable "vault_transit_key" {
  type        = string
  description = "Vault Transit key for database encryption at rest"
}

variable "environment" {
  type        = string
  description = "Deployment environment"
}
