# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault PKI and database engine configuration for payments-portal

# --- PKI: web-to-api (web-frontend → api-service) ---

resource "vault_mount" "pki_payments_portal" {
  path                      = "pki/payments-portal"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_payments_portal_intermediate" {
  backend     = vault_mount.pki_payments_portal.path
  type        = "internal"
  common_name = "payments-portal Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "web_frontend" {
  backend          = vault_mount.pki_payments_portal.path
  name             = "web-frontend"
  allowed_domains  = ["web-frontend.payments-portal-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "api_service" {
  backend          = vault_mount.pki_payments_portal.path
  name             = "api-service"
  allowed_domains  = ["api-service.payments-portal-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- Database engine: api-to-db (api-service → database) ---

resource "vault_mount" "db_payments_portal" {
  path = "database/payments-portal"
  type = "database"
}

resource "vault_database_secret_backend_connection" "database" {
  backend       = vault_mount.db_payments_portal.path
  name           = "database"
  allowed_roles  = ["api-service"]

  postgresql {
    connection_url = "postgresql://{{username}}:{{password}}@database.payments-portal-prod.svc:5432/payments-portal?sslmode=verify-full"
  }
}

resource "vault_database_secret_backend_role" "api_service" {
  backend             = vault_mount.db_payments_portal.path
  name                = "api-service"
  db_name             = vault_database_secret_backend_connection.database.name
  default_ttl         = 1800
  max_ttl             = 7200
  creation_statements = [
    "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}' IN ROLE \"api-service\";"
  ]
}
