# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault policies for payments-portal components
# Compliance scope: pci-dss

# --- Policy: web-frontend ---
path "kv/data/payments-portal/web-frontend/*" {
  capabilities = ["read", "list"]
}

path "pki/payments-portal/issue/web-frontend" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/payments-portal" {
  capabilities = ["update"]
}
path "transit/decrypt/payments-portal" {
  capabilities = ["update"]
}

# --- Policy: api-service ---
path "kv/data/payments-portal/api-service/*" {
  capabilities = ["read", "list"]
}

path "pki/payments-portal/issue/api-service" {
  capabilities = ["create", "update"]
}

path "database/creds/api-service" {
  capabilities = ["read"]
}

path "transit/encrypt/payments-portal" {
  capabilities = ["update"]
}
path "transit/decrypt/payments-portal" {
  capabilities = ["update"]
}

# --- Policy: database ---
path "kv/data/payments-portal/database/*" {
  capabilities = ["read", "list"]
}

path "database/config/payments-portal-database" {
  capabilities = ["read"]
}
path "sys/mounts/database/payments-portal" {
  capabilities = ["read"]
}
