# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault PKI and database engine configuration for digital-banking-platform

# --- PKI: gateway-to-account (api-gateway → account-service) ---

resource "vault_mount" "pki_digital_banking_platform" {
  path                      = "pki/digital-banking-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_digital_banking_platform_intermediate" {
  backend     = vault_mount.pki_digital_banking_platform.path
  type        = "internal"
  common_name = "digital-banking-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "api_gateway" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "api-gateway"
  allowed_domains  = ["api-gateway.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "account_service" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "account-service"
  allowed_domains  = ["account-service.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- PKI: gateway-to-payment (api-gateway → payment-service) ---

resource "vault_mount" "pki_digital_banking_platform" {
  path                      = "pki/digital-banking-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_digital_banking_platform_intermediate" {
  backend     = vault_mount.pki_digital_banking_platform.path
  type        = "internal"
  common_name = "digital-banking-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "api_gateway" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "api-gateway"
  allowed_domains  = ["api-gateway.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "payment_service" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "payment-service"
  allowed_domains  = ["payment-service.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- PKI: gateway-to-auth (api-gateway → auth-service) ---

resource "vault_mount" "pki_digital_banking_platform" {
  path                      = "pki/digital-banking-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_digital_banking_platform_intermediate" {
  backend     = vault_mount.pki_digital_banking_platform.path
  type        = "internal"
  common_name = "digital-banking-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "api_gateway" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "api-gateway"
  allowed_domains  = ["api-gateway.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "auth_service" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "auth-service"
  allowed_domains  = ["auth-service.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- Database engine: account-to-db (account-service → postgres-accounts) ---

resource "vault_mount" "db_digital_banking_platform" {
  path = "database/digital-banking-platform"
  type = "database"
}

resource "vault_database_secret_backend_connection" "postgres_accounts" {
  backend       = vault_mount.db_digital_banking_platform.path
  name           = "postgres-accounts"
  allowed_roles  = ["account-service"]

  postgresql {
    connection_url = "postgresql://{{username}}:{{password}}@postgres-accounts.digital-banking-prod.svc:5432/digital-banking-platform?sslmode=verify-full"
  }
}

resource "vault_database_secret_backend_role" "account_service" {
  backend             = vault_mount.db_digital_banking_platform.path
  name                = "account-service"
  db_name             = vault_database_secret_backend_connection.postgres_accounts.name
  default_ttl         = 1800
  max_ttl             = 7200
  creation_statements = [
    "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}' IN ROLE \"account-service\";"
  ]
}

# --- Database engine: payment-to-db (payment-service → postgres-payments) ---

resource "vault_mount" "db_digital_banking_platform" {
  path = "database/digital-banking-platform"
  type = "database"
}

resource "vault_database_secret_backend_connection" "postgres_payments" {
  backend       = vault_mount.db_digital_banking_platform.path
  name           = "postgres-payments"
  allowed_roles  = ["payment-service"]

  postgresql {
    connection_url = "postgresql://{{username}}:{{password}}@postgres-payments.digital-banking-prod.svc:5432/digital-banking-platform?sslmode=verify-full"
  }
}

resource "vault_database_secret_backend_role" "payment_service" {
  backend             = vault_mount.db_digital_banking_platform.path
  name                = "payment-service"
  db_name             = vault_database_secret_backend_connection.postgres_payments.name
  default_ttl         = 1800
  max_ttl             = 7200
  creation_statements = [
    "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}' IN ROLE \"payment-service\";"
  ]
}

# --- PKI: payment-to-fraud (payment-service → fraud-detection) ---

resource "vault_mount" "pki_digital_banking_platform" {
  path                      = "pki/digital-banking-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_digital_banking_platform_intermediate" {
  backend     = vault_mount.pki_digital_banking_platform.path
  type        = "internal"
  common_name = "digital-banking-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "payment_service" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "payment-service"
  allowed_domains  = ["payment-service.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "fraud_detection" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "fraud-detection"
  allowed_domains  = ["fraud-detection.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

# --- PKI: payment-to-notification (payment-service → notification-service) ---

resource "vault_mount" "pki_digital_banking_platform" {
  path                      = "pki/digital-banking-platform"
  type                      = "pki"
  default_lease_ttl_seconds = 86400
  max_lease_ttl_seconds     = 259200
}

resource "vault_pki_secret_backend_intermediate_cert_request" "pki_digital_banking_platform_intermediate" {
  backend     = vault_mount.pki_digital_banking_platform.path
  type        = "internal"
  common_name = "digital-banking-platform Intermediate CA"
  key_type    = "ec"
  key_bits    = 256
}

resource "vault_pki_secret_backend_role" "payment_service" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "payment-service"
  allowed_domains  = ["payment-service.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}

resource "vault_pki_secret_backend_role" "notification_service" {
  backend          = vault_mount.pki_digital_banking_platform.path
  name             = "notification-service"
  allowed_domains  = ["notification-service.digital-banking-prod.svc"]
  allow_subdomains = false
  allow_bare_domains = true
  allow_glob_domains = false
  allow_wildcard_certificates = false
  enforce_hostnames = true
  key_type         = "ec"
  key_bits         = 256
  max_ttl          = "72h"
  ttl              = "24h"
}
