# ============================================================
# GENERATED BY: CALM Forge v0.2
# DO NOT EDIT — regenerate from CALM source
# ============================================================

# Vault policies for digital-banking-platform components
# Compliance scope: pci-dss

# --- Policy: api-gateway ---
path "kv/data/digital-banking-platform/api-gateway/*" {
  capabilities = ["read", "list"]
}

path "pki/digital-banking-platform/issue/api-gateway" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/digital-banking-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/digital-banking-platform" {
  capabilities = ["update"]
}

# --- Policy: account-service ---
path "kv/data/digital-banking-platform/account-service/*" {
  capabilities = ["read", "list"]
}

path "pki/digital-banking-platform/issue/account-service" {
  capabilities = ["create", "update"]
}

path "database/creds/account-service" {
  capabilities = ["read"]
}

path "transit/encrypt/digital-banking-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/digital-banking-platform" {
  capabilities = ["update"]
}

# --- Policy: payment-service ---
path "kv/data/digital-banking-platform/payment-service/*" {
  capabilities = ["read", "list"]
}

path "pki/digital-banking-platform/issue/payment-service" {
  capabilities = ["create", "update"]
}

path "database/creds/payment-service" {
  capabilities = ["read"]
}

path "transit/encrypt/digital-banking-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/digital-banking-platform" {
  capabilities = ["update"]
}

# --- Policy: notification-service ---
path "kv/data/digital-banking-platform/notification-service/*" {
  capabilities = ["read", "list"]
}

path "pki/digital-banking-platform/issue/notification-service" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/digital-banking-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/digital-banking-platform" {
  capabilities = ["update"]
}

# --- Policy: fraud-detection ---
path "kv/data/digital-banking-platform/fraud-detection/*" {
  capabilities = ["read", "list"]
}

path "pki/digital-banking-platform/issue/fraud-detection" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/digital-banking-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/digital-banking-platform" {
  capabilities = ["update"]
}

# --- Policy: auth-service ---
path "kv/data/digital-banking-platform/auth-service/*" {
  capabilities = ["read", "list"]
}

path "pki/digital-banking-platform/issue/auth-service" {
  capabilities = ["create", "update"]
}

path "transit/encrypt/digital-banking-platform" {
  capabilities = ["update"]
}
path "transit/decrypt/digital-banking-platform" {
  capabilities = ["update"]
}

# --- Policy: redis-cache ---
path "kv/data/digital-banking-platform/redis-cache/*" {
  capabilities = ["read", "list"]
}

# --- Policy: postgres-accounts ---
path "kv/data/digital-banking-platform/postgres-accounts/*" {
  capabilities = ["read", "list"]
}

path "database/config/digital-banking-platform-postgres-accounts" {
  capabilities = ["read"]
}
path "sys/mounts/database/digital-banking-platform" {
  capabilities = ["read"]
}

# --- Policy: postgres-payments ---
path "kv/data/digital-banking-platform/postgres-payments/*" {
  capabilities = ["read", "list"]
}

path "database/config/digital-banking-platform-postgres-payments" {
  capabilities = ["read"]
}
path "sys/mounts/database/digital-banking-platform" {
  capabilities = ["read"]
}
